GPflow/GPflow

GPflow/param.py, testing/test_param.py
=> made tf_mode work for paramlist, added appropriate test

GPflow/model.py, testing/test_kerns.py, testing/test_likelihoods.py, testing/test_model.py
Improved test coverage of likelihoods, kernel and model.
=> Test improvements

README.md
I think the attached table makes a nice addition to the README.
=> table of methods for README

GPflow/model.py, GPflow/param.py, testing/test_model.py
As suggested by @pabloleon in #42
=> added autoflow methods to compute the likelihood (and the prior)

GPflow/conditionals.py, GPflow/gpmc.py, GPflow/gpr.py, GPflow/kernels.py, GPflow/likelihoods.py, GPflow/mean_functions.py, GPflow/model.py, GPflow/param.py, GPflow/priors.py, GPflow/svgp.py, GPflow/vgp.py, testing/test_kerns.py, testing/test_param.py, testing/test_priors.py, testing/test_variational.py
I think nowadays it fairly simple to keep Python 2/3 cross compatibility, so that would be nice. Here are some changes I needed to make before the package worked on Python 3.5.
=> Syntax changes for Python 3 compatibility

GPflow/transforms.py, testing/test_transforms.py
This PR adds a logistic transform to the transforms file, which allows the user to constrain a variables to between `a` and `b`.
=> Logistic transform

GPflow/transforms.py, testing/test_transforms.py
Hi @jameshensman we need to redo this pull request after the git problems this morning please. Could you check it is still what we want? Thanks,
Alex
=> Readding logistic transform.

GPflow/model.py, testing/test_autoflow.py
=> Autoflow fix bugfix

GPflow/densities.py, GPflow/priors.py, testing/test_priors.py
This PR adds a Laplace density and prior object, with appropriate test also.
=> adding a Laplace prior

GPflow/kernels.py, GPflow/likelihoods.py
Some simple changes to use `tf.fill` were appropriate, instead of creating an array ones ones and then multiplying by a constant.
=> Fill constants

GPflow/param.py, testing/test_autoflow.py
=> initializing all tf variables inside AF session

GPflow/transforms.py
In response to #119 (thanks @hughsalimbeni) this seems to fix the issue.
=> improvements to transforms

GPflow/vgp.py, testing/test_method_equivalence.py
This is equivalent to #125 , but on GPflow's repo so that the tests etc can run.
=> Correction to VGP form @fujiisoup

GPflow/model.py
This improves the numerical stability on calls to predict_f_samples
=> adding slight jitter to cholesky when computing samples

GPflow/transforms.py, testing/test_pickle.py
in response to #133 , added get/set state methods to allow pickling of logistic. A new test ensures that all transforms can be pickled safely.
=> made transforms all pickleable

GPflow/param.py, testing/test_likelihoods.py
Specifically, I tested these with python 3.5
=> some small edits to keep GPflow working with python 3

GPflow/kernels.py, GPflow/param.py, testing/test_pickle.py
=> make kernels with active_dims pickleable

GPflow/likelihoods.py, testing/test_likelihoods.py
Fixes #161 based on workaround for bug in TensorFlow.
Includes regression test.
=> Fixes #161

setup.py
I felt compelled to fix #173. I couldn't test this on a machine with gcc5 though.
=> Fixed compile bug when using gcc5.

.coveragerc, GPflow/_settings.py, GPflow/conditionals.py, GPflow/gpflowrc, GPflow/gpmc.py, GPflow/model.py, GPflow/sgpr.py, GPflow/svgp.py, testing/test_transforms.py
=> Verbosity flags for optimisation and compilation now used

GPflow/_settings.py, doc/source/index.rst, doc/source/notebooks/settings-demo.ipynb, doc/source/notebooks/settings.ipynb, testing/test_config.py
Settings can now be modified while running. Needs a bit more work.
=> Settings module now has ability to change during a run

GPflow/kernels.py, testing/test_kerns.py
=> Added polynomial kernel

GPflow/conditionals.py, GPflow/kullback_leiblers.py, GPflow/vgp.py, testing/test_param.py
All tests succeed with these small changes.
- Removed the batch_ prefix from all except matmul
- Tensor class has moved to tf.
Ran 195 tests in 187.652s
OK
=> Fixes for TF 0.11

GPflow/vgp.py, testing/test_methods.py
Fix to enable optimize_tf for vgp.
=> Added return statements in vgp._compile().

README.md
this is the in-house edition of #215
=> Jviereck patch 1

GPflow/kernels.py
I hope this clears up the discussion we've been having, @alexisboukouvalas , @markvdw
=> improvements to doctring of kernels regarding slices

README.md, doc/source/intro.rst
=> Correcting a typo in readme.

README.md, doc/source/intro.rst
Some updates to correct elements of readme that are out of date.
=> Updates to readme file.

README.md, doc/source/intro.rst
Shorten the readme and make a clearer reference to the documentation. Add a bibtex file for citations.
=> Bibtex docs

GPflow/model.py
Feed dict needs to be updated on each iteration.
Fixes #281.
@jameshensman #284 is proving fiddly to get a clean minimal test for. It seems a bit extreme to delay this one line bug fix which has already been released, so I suggest that if you agree we merge the fix and I continue to work on #284 next week.
=> Stochastic gradient fix

GPflow/hmc.py
as suggested in #292 by @john-bradshaw
=> minor updates to hmc.py

doc/source/notebooks/SGPR_notes.ipynb
@jameshensman  I noticed a math typo in this notebook.
=> Sgpr notes

Dockerfile, README.md
=> Docker file.

README.md, doc/source/apiAndArchitecture.rst, doc/source/conf.py, doc/source/derivations.rst, doc/source/index.rst, doc/source/intro.rst, doc/source/tutorialsAndExamples.rst
I've had a tidy up and restructure of the docs. The feedback we were getting is that people had difficulty finding things they were looking for. 
I've added some depth to the doctree in order to make this clearer.
I've made some graphical changes that make the whole thing much more approachable. 
I've fixed some errors and out of date stuff.
=> Fresh docs

docs_require.txt
Small tweak to requirements for docs.
=> Requirements tweak.

docs_require.txt
Still trying to fix read the docs problem.
=> Newer version of nbsphinx.

doc/source/model_options.rst
=> Tweak of a typo in docs.

GPflow/model.py, GPflow/param.py, testing/test_mean_functions.py, testing/test_param.py
Internal version of @tfwnicholson pull request to allow continuous integration.
=> Multiple params

docs_require.txt
A one line fix to make the docs build. Fixes #386 .
=> Correcting python version in docs require.

GPflow/conditionals.py, GPflow/ekernels.py, GPflow/gplvm.py, GPflow/gpr.py, GPflow/kernels.py, GPflow/sgpr.py, GPflow/vgp.py
internal edition of #391, courtesy of @dustinvtran
=> use transpose_{a,b}=True in tf.matmul's

GPflow/kernels.py, testing/reference.py, testing/test_kerns.py
=> mlp kernel

GPflow/param.py, testing/test_param.py
=> Mrksr fix randomize without prior

GPflow/kernels.py, testing/test_kerns.py
=> Mrksr fix mlp acos numerics

README.md, doc/source/intro.rst
@jameshensman we should probably update the reference to the paper to the peer reviewed version, no?
=> Update bibtex for GPflow paper.

GPflow/densities.py, GPflow/ekernels.py, GPflow/gplvm.py, GPflow/kernels.py, GPflow/kullback_leiblers.py, GPflow/sgpr.py, GPflow/tf_wraps.py
Also removes tf_wraps.eye, which used diag, and has been deprecated for several version numbers now.
=> changing all instances of diag(_part) to matrix_diag(_part)

GPflow/likelihoods.py
A cleaned-up and internal version of #368
=> adding binsize (and explanation) to Poisson likelihood

GPflow/param.py, GPflow/transforms.py
In house version of #469, so the unittests run. Thanks @ialong.
=> Param reshape

contributing.md
Some elaboration on how to contribute, and what to do when contributions are valuable, but perhaps won't make it into GPflow for whatever reason.
=> Added elaboration on how to contribute

README.md
List projects using GPflow. This address #407
=> List projects using GPflow on main page

MANIFEST.in
=> Remove old references to tf_ops

RELEASE.md
Hello everyone,
As soon as this PR is merged, I will create tag / release for GPflow.
=> Release 0.4.0 message update

gpflow/ekernels.py, gpflow/kernels.py, testing/test_ekerns.py
Hi everybody,
This is a pull request for computing the expectation `<x_t k(x_t, Z)>_q(X)`. Currently `exKxz` computes `<x_{t-1}k(x_t, Z)>_q(X)` which is basically the pair-wise expectation of two consecutive time steps. I believe this is useful in some dynamic systems that need to compute the expectation between two time steps. However the name of the function is a bit misleading and also the functionality of it is not in alignment with the general expectation terms.
This pull request handles both cases. The old function has been renamed to `exKxz_pairwise` and now the `exKxz` computes the `<x_t k(x_t, Z)>_q(X)`. I could have opted for the reverse naming, e.g., `exKxz` and `exKxz_non_pairwise` but that would be misleading. Tests are modified in order to pass with both cases now.
Currently …
=> added correct expectation for exKxz. all tests pass

gpflow/params/parameter.py, gpflow/params/parameterized.py
informally approved by @markvdw 
example:
```
In [7]: m = gpflow.models.GPR(X, Y, k)
In [8]: print(m)
<Parameter name:GPR/likelihood/variance [trainable] transform:+ve prior:None shape:()>
value: 1.0
<Parameter name:GPR/kern/variance [trainable] transform:+ve prior:None shape:()>
value: 1.0
<Parameter name:GPR/kern/lengthscales [trainable] transform:+ve prior:None shape:()>
value: 0.2
```
=> Print 1.0RC

gpflow/kernels.py, gpflow/models/svgp.py
Currently incorrect data types can be assigned.
=> Ensure dtypes are followed when assigning parameters

gpflow/params/parameter.py, tests/test_param.py
Now tested.
Question: is there (or should there be) a test to compare setting of the same parameter in different sessions with different values?
=> adding value property

gpflow/decors.py, gpflow/misc.py, gpflow/params/parameter.py, gpflow/params/parameterized.py, gpflow/training/optimizer.py, gpflow/training/scipy_optimizer.py, gpflow/training/tensorflow_optimizer.py, tests/test_optimizers.py
Whenever `autoflow` or `optimizers` call initializing, it shall be called without coercion.
=> Initializing must not be persevering.

tests/test_likelihoods.py
```
=========================== slowest 5 test durations ===========================
417.60s call     tests/test_likelihoods.py::TestLikelihoodChecks::test_likelihood_checks
166.69s call     tests/test_ekerns.py::TestKernExpQuadrature::test_exKxz_pairwise
148.19s call     tests/test_gplvm.py::TestBayesianGPLVM::test_kernelsActiveDims
65.70s call     tests/test_hmc.py::CheckTrainingVariableState::test_multiple_runs
48.64s call     tests/test_coregion.py::TestEquivalence::test_predicts
```
Likelihood tests take extremely long time. This PR fixes that by using `pytest` parameterize feature and running each likelihood example in different context.
=> Likelihood checks speed up.

tests/test_uncertain_conditional.py
Improvements for #577.
* Data generation separeted from tests.
* Code duplication removed.
* Not requires extra packages.
=> Improve uncertain conditional test

gpflow/densities.py, gpflow/models/gpr.py, tests/test_densities.py
=> fix vector handling and broadcasting in multivariate_normal density

gpflow/training/natgrad_optimizer.py
=> Fixed ModuleNotFoundError

doc/source/notebooks/natural_gradients.ipynb
an example notebook with some basic applications of nat grads
=> Natural gradients notebook

doc/source/notebooks/natural_gradients.ipynb
=> NatGrads notebook cleanup

tests/test_multioutput.py
A first test for mixed mok. more to follow
=> a first mixedmok test

contributing.md
=> Extend contributing.md

doc/source/notebooks/multioutput.ipynb, gpflow/conditionals.py, gpflow/models/sgpmc.py, gpflow/models/svgp.py, gpflow/multioutput/conditionals.py, gpflow/multioutput/features.py, gpflow/multioutput/kernels.py, tests/test_multioutput.py, tests/test_uncertain_conditional.py
`full_output_cov` makes more sense and has shorter tab-completion
=> rename full_cov_output to full_output_cov

gpflow/likelihoods.py, gpflow/quadrature.py, gpflow/saver/coders.py, gpflow/test_util.py, setup.py, tests/test_likelihoods.py, tests/test_quadrature.py
Better numerical stability for predict_density().
More tests.
=> ndiagquad logspace feature for improved numerical stability

gpflow/quadrature.py
Improves the documentation of ndiagquad.
=> extended docstring for ndiagquad

docs_require.txt, gpflow/kernels.py
Update docs_require.txt to supported tensorflow version
=> Update docs_require.txt to supported tensorflow version

.travis.yml
=> Travis jobs

README.md
Adding instructions to compile documentation locally as this is currently missing.
=> Update README to include local compilation of docs

doc/source/notebooks/tips_and_tricks.ipynb, tests/test_notebooks.py
=> Tips and tricks notebook

doc/source/notebooks/tips_and_tricks.ipynb
=> Tips & Tricks notebooks changes

doc/README.md, doc/source/notebooks/tips_and_tricks.ipynb, doc/source/tutorialsAndExamples.rst
This cleans up some of the explanations in the Tips & Tricks notebook, adds them to the API documentation, and adds a README for the doc/ subdirectory that has links to readthedocs and how to build it locally.
=> Minor changes to Tips & Tricks notebook

gpflow/conditionals.py, gpflow/misc.py, gpflow/multioutput/conditionals.py, tests/test_misc.py
Added new method leading_transpose which allow to shuffle the tensor with leading dimensions, considering them as one group.
=> Leading transpose

gpflow/models/model.py, tests/test_likelihoods.py
This fixes the bug brought up in issue #951.
=> SwitchedLikelihood workaround for #951

README.md
added link to upcoming ICML paper on DGPs with Importance-Weighted VI.
=> Update README.md with link to upcoming ICML paper 

.circleci/config.yml
=> Upate Dockerfile version in CircleCI config file

gpflow/misc.py, tests/test_param.py
=> Change misc.initialize_variables() to not keep adding ops to the graph

doc/source/notebooks/tips_and_tricks.ipynb
Checking for:
mistakes/typos
house style/formatting
consistency
sufficient (or missing) cross-linkage between documents
clarify unclear sections/explanations
(See https://prowlerio.atlassian.net/browse/PTKB-6960)
=> GPFlow manual copyedit - tips and tricks page

gpflow/utilities/utilities.py, tests/test_printing.py
Fixing printing for Lists and Dict. Particularly affects printing of combination kernels
=> print_summary now deals with list and dict of tf.Module

.gitignore, gpflow/kernels.py, tests/reference.py, tests/test_kerns.py
This is a proposed **enhancement** which introduces periodic versions of the Matern family of kernels, to supplement the standard SE-based one. I have found these to be useful to have in my toolkit since the ubiquitous SE one is often too darn smooth!
=> Periodic++

gpflow/likelihoods/robustmax.py
Makes some numerics fudge factors more explicit, and the code slightly easier to read. No functional changes.
=> Minor RobustMax cleanup

tests/test_likelihoods.py
The quadrature tests for likelihoods all checked whether `predict_density` was overwritten (i.e. analytic), but likelihoods can only overwrite some of `predict_density`, `variational_expectations`, `predict_mean_and_var` - so the tests were not comprehensive. This little PR has separate checks for "analytic" (quadrature fallback overwritten) for each of the three method tests.
=> make likelihood quadrature tests comprehensive

codecov.yml, gpflow/config/__config__.py, gpflow/inducing_variables/inducing_variables.py, gpflow/kernels/mo_kernels.py, gpflow/models/model.py, gpflow/optimizers/scipy.py, gpflow/utilities/ops.py, tests/test_config.py, tests/test_gplvm.py, tests/test_logdensities.py
=> Improve gpflow2 code coverage by adding tests

gpflow/utilities/utilities.py, tests/test_printing.py
Test on print_summary now checks string output straight
=> Test on print_summary now checks string output straight

doc/source/notebooks/advanced/natural_gradients.ipynb, tests/test_notebooks.py
=> Natural gradient notebook fix

doc/source/notebooks/tailor/kernel_design.ipynb, gpflow/__init__.py, gpflow/base.py, gpflow/inducing_variables/inducing_variables.py, gpflow/kernels/linears.py, gpflow/kernels/misc.py, gpflow/kernels/statics.py, gpflow/kernels/stationaries.py, gpflow/likelihoods/likelihoods.py, gpflow/models/gplvm.py, gpflow/models/svgp.py, gpflow/models/vgp.py, gpflow/utilities/__init__.py, gpflow/utilities/bijectors.py, tests/test_prior.py
* Move `positive` and `triangular` aliases to the bijector's utilities
* Create default value for the positive alias.
=> Update positive transform

doc/source/notebooks/advanced/convolutional.ipynb, doc/source/notebooks/advanced/kernels.ipynb, doc/source/notebooks/advanced/multioutput.ipynb, doc/source/notebooks/basics/GPLVM.ipynb, doc/source/notebooks/intro_to_gpflow2.ipynb, gpflow/config/__config__.py, gpflow/kernels/changepoints.py, gpflow/utilities/bijectors.py, gpflow/utilities/utilities.py, setup.py, tests/test_config.py, tests/test_prior.py
* Refactor config with the dataclass and enums
* Add an option for the positive transform bias
* Make the global config readable
=> Refactor config with a dataclass

README.md
Fixing mention of `develop-2.0` to `develop` in `README.md`.
=> Fix branch in README

gpflow/optimizers/natgrad.py
Fixes https://github.com/GPflow/GPflow/issues/1142
=> Remove persistent tape in natural gradient

README.md
=> Updated contributors

doc/source/notebooks/advanced/kernels.ipynb, gpflow/conditionals/util.py, gpflow/expectations/products.py, gpflow/expectations/sums.py, gpflow/kernels/__init__.py, gpflow/kernels/base.py, gpflow/kernels/misc.py, gpflow/kernels/periodic.py, tests/test_features.py, tests/test_gplvm.py, tests/test_kernels.py
This is a port of the generalized periodic kernel (introduced to v1.0 in #1052). I have not attempted to make this one backward compatible as it would be part of v2.0 and therefore assuming a breaking change is ok (but I could be wrong).
=> Porting the generalized periodic kernel

gpflow/conditionals/util.py
Boring but important doc error
=> quick fix of documentation mathematics

gpflow/config/__config__.py
=> Fixes #1080 by casting tensorflow dtypes to numpy dtypes

gpflow/utilities/utilities.py, tests/test_printing.py
Fixes #1117. Only displays prior *name*, not any parameters.
=> add prior to print_summary

gpflow/kernels/base.py, gpflow/kernels/mo_kernels.py
Addresses several points in #1086
=> Clean up kernel interface

gpflow/conditionals/conditionals.py, gpflow/conditionals/mo_conditionals.py, gpflow/conditionals/uncertain_conditionals.py, gpflow/conditionals/util.py, gpflow/covariances/mo_kuus.py, gpflow/expectations/cross_kernels.py, gpflow/expectations/linears.py, gpflow/expectations/misc.py, gpflow/expectations/squared_exponentials.py, gpflow/kullback_leiblers.py, gpflow/likelihoods/likelihoods.py, gpflow/logdensities.py, gpflow/models/model.py, gpflow/models/svgp.py, gpflow/optimizers/natgrad.py
* [Title](#title)
We prepare the code base to support usage of dynamic shapes and tf.function with unknown sizes.
* Bad example: `This is a bug-fix found at #1179.`
* Good example: `We allow usage of tf.function with unknown sizes.`
TODO: dedicated tests
=> From static shapes to dynamic shapes

README.md
=> Update README.md: GPflow slack invite, stackoverflow vs github issues, installation instructions

gpflow/likelihoods/likelihoods.py, gpflow/likelihoods/robustmax.py
Saves @jameshensman's answer from #1202 in code so we won't have to answer similar ones again...
=> Improve explanation of RobustMax likelihood

gpflow/optimizers/scipy.py
Added docs for method parameter
=> Added docs for method parameter

gpflow/optimizers/scipy.py
Fix type declaration for LossClosure
=> Fix type declaration for LossClosure

doc/source/notebooks/advanced/varying_noise.pct.py, gpflow/optimizers/natgrad.py
Put natgrads back into the varying noise notebook.
Resolves #1173
=> use natgrad optimizer in varying noise notebook

gpflow/kullback_leiblers.py, tests/gpflow/test_kullback_leiblers.py
=> Add option to pass K_cholesky to gauss_kl

doc/source/notebooks/advanced/convolutional.pct.py, gpflow/covariances/kufs.py, gpflow/covariances/kuus.py, gpflow/kernels/convolutional.py, gpflow/kernels/periodic.py, tests/gpflow/covariances/test_base_covariances.py, tests/gpflow/kernels/test_kernels.py, tests/gpflow/models/test_gplvm.py
Periodic kernel: base -> base_kernel
Convolutional kernel: basekern -> base_kernel, img_size -> img_shape, patch_size -> patch_shape
=> Rename base kernel in Periodic and Convolutional Kernel to base_kernel

doc/source/notebooks/advanced/coregionalisation.pct.py, doc/source/notebooks/advanced/mcmc.pct.py, doc/source/notebooks/advanced/multiclass_classification.pct.py, doc/source/notebooks/advanced/multioutput.pct.py, doc/source/notebooks/advanced/variational_fourier_features.pct.py, doc/source/notebooks/advanced/varying_noise.pct.py, doc/source/notebooks/tailor/gp_nn.pct.py, tests/integration/test_notebooks.py
Notebook tests were silently deactivated by #1288.
This PR a) fixes the notebook test, b) adds another test to ensure this can't happen again, and c) fixes the notebooks for the PRs that have since made it into `develop`.
=> Reactivate notebook tests

doc/source/notebooks/advanced/variational_fourier_features.pct.py, gpflow/conditionals/conditionals.py, gpflow/conditionals/mo_conditionals.py, gpflow/covariances/mo_kufs.py, gpflow/covariances/mo_kuus.py, gpflow/expectations/quadratures.py, gpflow/expectations/squared_exponentials.py, gpflow/kernels/base.py, gpflow/kernels/changepoints.py, gpflow/kernels/mo_kernels.py, gpflow/models/gplvm.py, gpflow/models/gpr.py, gpflow/models/sgpr.py, gpflow/models/vgp.py, tests/gpflow/expectations/test_expectations.py, tests/gpflow/kernels/test_broadcasting.py, tests/gpflow/kernels/test_kernels.py
=> rename kernel full to full_cov

gpflow/base.py, gpflow/models/model.py, tests/gpflow/models/test_gpr.py, tests/gpflow/test_base_prior.py
=> log_prior -> log_prior_density

doc/source/notebooks/advanced/convolutional.pct.py, doc/source/notebooks/advanced/gps_for_big_data.pct.py, doc/source/notebooks/advanced/mcmc.pct.py, doc/source/notebooks/advanced/natural_gradients.pct.py, doc/source/notebooks/advanced/variational_fourier_features.pct.py, doc/source/notebooks/advanced/varying_noise.pct.py, doc/source/notebooks/intro_to_gpflow2.pct.py, doc/source/notebooks/tailor/external-mean-function.pct.py, doc/source/notebooks/theory/Sanity_check.pct.py, doc/source/notebooks/theory/upper_bound.pct.py, doc/source/notebooks/understanding/models.pct.py, gpflow/__init__.py, gpflow/base.py, gpflow/utilities/utilities.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/kernels/test_coregion.py, tests/gpflow/models/test_gpr.py, tests/gpflow/models/test_svgp.py, tests/gpflow/optimizers/test_natural_gradient.py, tests/gpflow/utilities/test_printing.py, tests/integration/test_dynamic_shapes.py, tests/integration/test_method_equivalence.py
delete `Parameter.trainable` setter, for #1184 , **at least I think this was the intended action. let me know if not**
=> remove trainable setter on Parameter

gpflow/models/gpmc.py, gpflow/models/model.py, gpflow/models/sgpmc.py, gpflow/models/vgp.py
Suggestions I was thinking of.
=> some changes to incorporate multioutput

gpflow/models/gplvm.py, gpflow/models/gpmc.py, gpflow/models/gpr.py, gpflow/models/model.py, gpflow/models/sgpmc.py, gpflow/models/sgpr.py, gpflow/models/svgp.py, gpflow/models/vgp.py
Resolves #1248, resolves #1249, and addresses several points in #1252.
=> Clean up type annotations and doc strings

doc/source/notebooks/gpflow2_upgrade_guide.md
Fixes the section on Parameter.value/numpy.
=> Quickfix for gpflow2 upgrade guide

doc/source/notebooks/theory/upper_bound.pct.py, gpflow/optimizers/scipy.py, gpflow/utilities/utilities.py, tests/gpflow/optimizers/test_scipy.py, tests/integration/test_dynamic_shapes.py
=> rename jit -> compile

doc/source/notebooks/intro_to_gpflow2.pct.py
=> Add a section about custom user config

README.md
Some bits were still a bit out of date...
=> update README for 2.0 release

doc/source/notebooks/tailor/external-mean-function.pct.py
Replicate the original experimental setup published in Fortuin and Ratsch (2019) and heavily comment the code with references to the paper.
Changes were made after confirming via an email correspondence with the author of the [reference paper](https://arxiv.org/abs/1901.08098), Vincent Fortuin.
I have tested these changes on a notebook I downloaded from https://github.com/GPflow/docs/pull/2.
However, the problem is that now each epoch takes 7 minutes instead of 7 seconds. With 5 epochs (instead of the original 100) this is around half an hour.
For details, look at the code quality requirements section in [contributing.md](../contributing.md). The *main* points are repeated here:
* _New feature's_ code must be accompanied with [detailed](../contributing.md) docstrings.
* _New features_ …
=> Match original experimental setup for "metalearning with GPs" notebook.

doc/source/notebooks/gpflow2_upgrade_guide.md
add likelihood section, predict_log_density, IsotropicStationary
=> Add some missing sections to gpflow2 upgrade guide

gpflow/ci_utils.py, mypy.ini
=> add mypy to test requirements; type ci utils module

doc/source/intro.rst
Fixes the broken link reported in #1428.
=> fix link in sphinx intro.rst

doc/source/notebooks/advanced/changepoints.pct.py, doc/source/notebooks/advanced/multioutput.pct.py
=> fix kernel construction in multioutput notebook

setup.py
Will give us a much nicer landing page on https://pypi.org/project/gpflow/
=> add long_description and project_urls to setup.py

.gitignore, doc/source/notebooks/advanced/variational_fourier_features.pct.py, gpflow/base.py, gpflow/covariances/kufs.py, gpflow/probability_distributions.py, setup.py
does #1368 for probability distributions
required a fix for `TensorLike` problem for multiple dispatch
=> add type hints for probability distributions

gpflow/kernels/changepoints.py, tests/gpflow/kernels/test_changepoints.py
=> Fix dimensions of kernel evaluation of changepoint kernel

doc/source/notebooks/advanced/ordinal_regression.pct.py, gpflow/models/gplvm.py, gpflow/models/gpr.py, gpflow/models/sgpmc.py, gpflow/models/sgpr.py, gpflow/models/util.py, gpflow/models/vgp.py, tests/gpflow/utilities/test_utilities.py
Addresses https://github.com/GPflow/GPflow/issues/1439
=> Convert data structures to tensor in model init method

gpflow/models/gpmc.py
PR #1452 didn't extend the bugfix of #1439 to GPMC model, fixed by this.
=> #1452 for GPMC model

gpflow/base.py, tests/gpflow/test_base.py
=> add type hints: base

gpflow/inducing_variables/inducing_variables.py, gpflow/inducing_variables/multioutput/inducing_variables.py
does #1368 for `inducing_variables`
=> add type hints: inducing_variables

gpflow/models/gpr.py
Updated documentation for models.gpr according to my suggestion in this [issue](https://github.com/GPflow/docs/issues/4).
=> updated models.gpr docstring

README.md
Added project to the list of projects that use GPflow that does GPs for molecules!
=> Update readme with new project using GPflow

.circleci/config.yml, setup.py
=> check dependency versions are valid on CI

gpflow/quadrature/deprecated.py, tests/gpflow/quadrature/test_quadrature.py
Fix for issue #1547 with accompanying test.
@pio-neil ^
=> Fix for quadrature failure mode when autograph was set to False

tests/integration/test_method_equivalence.py
Changes the test such that it would have caught the bug fixed by #1560 before...
=> Bugfix: add regression test

gpflow/models/model.py
=> Explicit NotImplementedError on predict_y/predict_log_density with full_(output_)cov=True

.github/ISSUE_TEMPLATE/bugs-performance-issues.md, .github/ISSUE_TEMPLATE/config.yml
* automatically add bug reports to the bug project board
* disable blank issues
=> Update issue templates

doc/source/notebooks/intro_to_gpflow2.pct.py
=> update intro_to_gpflow2 notebook to account for saved_model now working

README.md
List the trieste project
list trieste as downstream project
=> list trieste as downstream project

README.md
list structured-dgp project
**Fully backwards compatible:** yes 
list structured-dgp as downstream project
=> list structured-dgp as downstream project

gpflow/models/gpr.py
This PR gives the `GPR` class an `_add_noise_cov` method. Apart from removing code duplication between `log_marginal_likelihood` and `predict_f`, this also makes the class more flexible: it now allows downstream models to implement GP regression with a full-matrix likelihood covariance without having to duplicate any code, simply by overriding `_add_noise_cov`.
* New `_add_noise_cov` method in `gpflow.models.GPR`
=> _add_noise_cov method to make GPR model class more extensible

README.md
so that it will render correctly on PyPI
=> Change URL for GPflow logo in README.md to absolute

RELEASE.md
Will make it easier for people looking at release notes to get more details on the changes.
=> Add PR references to release notes

.circleci/config.yml, CONTRIBUTORS.md, RELEASE.md
**Related issue(s)/PRs:** N/A
* Install dependencies into virtual environments, to avoid conflicts with pre-installed packages.
* Fix the version of Tensorflow and Tensorflow Probability used on CircleCi, to fix issue where the current `latest` versions aren't compatible.
* Consistently use the newest version of `pip` on CircleCi.
* Consistently turn off progress bars in `pip` on CircleCi, as progress bars are not useful in logs.
* Constrain the version of Tensorflow / Tensorflow Probability in our `setup.py`.
N/A
N / A
=> Fix broken CircleCi build.

CONTRIBUTORS.md, README.md, RELEASE.md
* Fix broken link in README.md
* Remove some trailing whitespaces.
Not doing anything thing and considering it somebody else's problem.
N/A
=> Fix broken link in README.md.

Makefile, RELEASE.md
**Related issue(s)/PRs:** N/A
Make `make dev-install` install the test requirements.
Not making any changes.
`make dev-install check-all`
=> Add test requirements to make dev-install.

RELEASE.md, gpflow/experimental/__init__.py, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/check_shapes.py, gpflow/experimental/utils.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/test_utils.py, tests_requirements.txt
**PR type:** new feature
Add a library for asserting / checking tensor shapes.
This is initially copied from a Secondmind internal project, and we'll probably want to iterate on it a bit before using it.
1. Not checking shapes at all.
2. Using `tf.debugging.assert_shapes`.
```python
>>> from gpflow.check_shapes import check_shapes
>>> import numpy as np
>>> @check_shapes(
...   ("x", ["n_rows", 1]),
...   ("return", []),
... )
... def f(x: np.ndarray) -> np.ndarray:
...     return x.sum()
... 
>>> f(np.ones((7, 1)))
7.0
>>> f(np.ones((7,)))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/jesper/src/GPflow/gpflow/check_shapes/check_shapes.py", line 254, in wrapped …
```
=> Add initial code for shape checking.

gpflow/base.py, gpflow/experimental/check_shapes/argument_ref.py, gpflow/experimental/check_shapes/base_types.py, gpflow/experimental/check_shapes/check_shapes.py, gpflow/experimental/check_shapes/errors.py, gpflow/experimental/check_shapes/inheritance.py, gpflow/experimental/check_shapes/specs.py, tests/gpflow/experimental/check_shapes/test_argument_ref.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_errors.py, tests/gpflow/experimental/check_shapes/test_inheritance.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/experimental/check_shapes/test_specs.py, tests/gpflow/experimental/check_shapes/utils.py
Refactor `check_shapes` into multiple files, and write some more tests.
=> Refactor check_shapes into multiple files.

gpflow/expectations/quadratures.py, gpflow/kernels/base.py, gpflow/kernels/changepoints.py, gpflow/kernels/convolutional.py, gpflow/kernels/linears.py, gpflow/kernels/misc.py, gpflow/kernels/multioutput/kernels.py, gpflow/kernels/periodic.py, gpflow/kernels/statics.py, gpflow/kernels/stationaries.py, mypy.ini, tests/gpflow/kernels/reference.py, tests/gpflow/kernels/test_broadcasting.py, tests/gpflow/kernels/test_changepoints.py, tests/gpflow/kernels/test_coregion.py, tests/gpflow/kernels/test_kernels.py, tests/gpflow/kernels/test_positive_semidefinite.py, tests/gpflow/kernels/test_scaled_euclid_dist.py
=> Add type hints to kernels.

gpflow/base.py, gpflow/conditionals/conditionals.py, gpflow/conditionals/dispatch.py, gpflow/conditionals/multioutput/conditionals.py, gpflow/conditionals/multioutput/sample_conditionals.py, gpflow/conditionals/sample_conditionals.py, gpflow/conditionals/uncertain_conditionals.py, gpflow/conditionals/util.py, mypy.ini, tests/gpflow/conditionals/test_broadcasted_conditionals.py, tests/gpflow/conditionals/test_conditionals.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/conditionals/test_uncertain_conditional.py, tests/gpflow/conditionals/test_util.py, tests_requirements.txt
Add type hints to conditionals.
=> Add type hints to conditionals.

gpflow/base.py
Fix type error discovered by mypy `0.940`.
=> Fix type error with mypy 0.940.

doc/generate_module_rst.py
Notice how the documentation for `gpflow.conditionals.multioutput.conditionals.separate_independent_conditional` is repeated multiple times in https://gpflow.github.io/GPflow/2.4.0/api/gpflow/conditionals/index.html#gpflow-conditionals-conditional
because it is registered for multiple different types fo multiple dispatch.
This PR merges those sections into one.
=> Don't repeat documentation for functions used multiple times in multiple-dispatch

CONTRIBUTING.md, MANIFEST.in, README.md, codecov.yml, doc/sphinx/notebooks/tailor/mixture_density_network.pct.py
Fix some links I broken when I refactored our documentation.
=> Fix some broken links.

gpflow/experimental/check_shapes/check_shapes.lark, gpflow/experimental/check_shapes/parser.py
Small simplification of the definition and parsing of argument references.
=> Simplify parsing of argument references.

.circleci/config.yml, Makefile, gpflow/__init__.py, gpflow/base.py, gpflow/kernels/misc.py, gpflow/mypy_flags.py, gpflow/quadrature/deprecated.py, gpflow/quadrature/gauss_hermite.py, gpflow/type_flags.py, tests/gpflow/conditionals/test_broadcasted_conditionals.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/expectations/test_expectations.py, tests/gpflow/kernels/reference.py, tests/gpflow/kernels/test_coregion.py, tests/gpflow/kernels/test_scaled_euclid_dist.py, tests/gpflow/likelihoods/test_heteroskedastic.py, tests/gpflow/likelihoods/test_heteroskedastic_constant_variance.py, tests/gpflow/likelihoods/test_multiclass.py, tests/gpflow/models/test_cglb.py, tests/gpflow/models/test_svgp.py, tests/gpflow/models/test_svgp_posterior.py, tests/gpflow/models/test_variational.py, tests/gpflow/optimizers/test_scipy.py, tests/gpflow/test_base_prior.py, tests/gpflow/test_kullback_leiblers.py, tests/gpflow/utilities/test_traversal.py, tests/integration/test_dynamic_shapes.py, tests/integration/test_method_equivalence.py
This has been tested with:
* Python 3.7 + Numpy 1.19
* Python 3.7 + Numpy 1.20
* Python 3.7 + Numpy 1.21
* Python 3.8 + Numpy 1.19
* Python 3.8 + Numpy 1.20
* Python 3.8 + Numpy 1.21
* Python 3.8 + Numpy 1.22
* Python 3.9 + Numpy 1.20
* Python 3.9 + Numpy 1.21
* Python 3.9 + Numpy 1.22
* Python 3.10 + Numpy 1.21
* Python 3.10 + Numpy 1.22
Fixes #1848
=> Fix problems with different versions of Python and Numpy.

.pylintrc, doc/sphinx/conf.py, doc/sphinx/examples, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/accessors.py, gpflow/experimental/check_shapes/checker.py, gpflow/experimental/check_shapes/checker_context.py, gpflow/experimental/check_shapes/config.py, gpflow/experimental/check_shapes/decorator.py, gpflow/experimental/check_shapes/error_contexts.py, gpflow/experimental/check_shapes/inheritance.py, gpflow/experimental/check_shapes/shapes.py, tests/examples/test_check_shapes_examples.py, tests/gpflow/experimental/check_shapes/test_argument_ref.py, tests/gpflow/experimental/check_shapes/test_checker.py, tests/gpflow/experimental/check_shapes/test_checker_context.py, tests/gpflow/experimental/check_shapes/test_decorator.py, tests/gpflow/experimental/check_shapes/test_inheritance.py, tests/gpflow/experimental/check_shapes/test_integration.py
Improve `check_shapes` documentation - mostly focussed on the `check_shapes` module landing page.
=> Iterate on check_shapes documentation.

doc/generate_module_rst.py
Fix logic of where functions and classes are placed in the documentation.
The previous logic was that objects are placed at the place closest to the root, where they are imported. This leads to weird behaviour, such as `gpflow.utilities.model_utils.add_noise_cov` being documented as `gpflow.posteriors.add_noise_cov`, just because it happens to be imported by `gpflow.posteriors`. The new logic only considers places where the object either is declared or added to `__all__`, which places `gpflow.utilities.model_utils.add_noise_cov` under `gpflow.utilities.add_noise_cov`.
=> Fix documentation import logic.

doc/sphinx/notebooks/advanced/mcmc.pct.py
=> MCMC notebook: demonstrate multi-modality in regression

doc/sphinx/notebooks/advanced/variational_fourier_features.pct.py, gpflow/base.py, gpflow/conditionals/conditionals.py, gpflow/conditionals/multioutput/conditionals.py, gpflow/conditionals/multioutput/sample_conditionals.py, gpflow/conditionals/sample_conditionals.py, gpflow/conditionals/uncertain_conditionals.py, gpflow/conditionals/util.py, gpflow/experimental/check_shapes/shapes.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/conditionals/test_uncertain_conditional.py
Add shape checks to the conditionals.
Partial: #1241
=> Add shape checks to the conditionals.

RELEASE.md, gpflow/expectations/expectations.py, gpflow/kernels/changepoints.py, gpflow/kernels/convolutional.py, gpflow/kernels/misc.py, gpflow/kernels/multioutput/kernels.py, gpflow/models/model.py, gpflow/models/training_mixins.py, gpflow/models/util.py, gpflow/optimizers/natgrad.py, gpflow/posteriors.py, gpflow/quadrature/gauss_hermite.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/likelihoods/test_heteroskedastic_constant_variance.py, tests/gpflow/optimizers/test_mcmc.py, tests/gpflow/optimizers/test_natural_gradient.py, tests/integration/test_dynamic_shapes.py, tests/integration/test_method_equivalence.py
Add the last shape checks to GPflow:
1. Optimisers.
2. Integration tests.
3. Various other bits...
4. Remove some unused variables and imports.
=> Add the last shape checks to GPflow.

.circleci/config.yml, benchmark/README.md, benchmark/metadata.py, benchmark/plotters.py, benchmark/registry.py, benchmark/run.py, benchmark/sharding.py, doc/README.md, tests/integration/test_benchmark.py
Our benchmarks time out when run. This paralellises them.
This is similar in spirit #1972 , but for benchmarks instead of documentation.
=> Run benchmarks in parallel.

RELEASE.md, gpflow/utilities/misc.py, gpflow/utilities/ops.py
=> Remove obsolete 'cast' function.

gpflow/experimental/check_shapes/shapes.py
I thought I had tested the previous version well, but when used in GPflux it didn't work. This seems to work...
Yeah - I don't know how to improve the unit tests for this - It partially depends on your TensorFlow probability versions, but honestly I also don't know what's going on between TensorFlow-Probability, Keras and GPflux.
=> More fix for the tfp..._TensorCoercible class.

doc/sphinx/notebooks/advanced/GPLVM.pct.py
Fix broken notebook that is causing our documentation-build to fail. For example:
https://app.circleci.com/pipelines/github/GPflow/GPflow/4641/workflows/23af5882-c718-439d-b66a-8b937b65aa7f/jobs/18693
=> Fix broken notebook.

RELEASE.md
Some typos in the RELEASE.md for the quick 2.6.4 bugfix patch.
=> Some corrections to RELEASE.md

CONTRIBUTORS.md, RELEASE.md, doc/sphinx/notebooks/getting_started/monitoring.pct.py
* Add example to monitoring notebook describing how to use `monitor` with the `Adam` optimizer
=> Add usage of monitoring with Adam to notebook

.circleci/config.yml
**PR type:** security issue
**Related issue(s)/PRs:** CircleCI had a [security issue](https://circleci.com/blog/january-4-2023-security-alert/) that requires some action
Change the CircleCI deploy key (that is what this PR is doing; there are other key rotations also required)
=> Rotated deploy key due to CircleCI security incident 2023-01-04

doc/sphinx/notebooks/advanced/multioutput.pct.py
fix two typos
**PR type:** bugfix / enhancement / new feature / doc improvement
* ...
* ...
* ...
```python
```
**Fully backwards compatible:** yes / no
=> DOC: fix typos

gpflow/config/__config__.py
**Related issue(s)/PRs:** related to [1985](https://github.com/GPflow/GPflow/pull/1985) 
The [wrapper](https://github.com/GPflow/GPflow/blob/awav/likelihoods-positive-minimum/gpflow/config/__config__.py#L97-L99) for config constants is implemented as an Enum, even though it's not really being used as an enumeration. More problematically, Enums don't work correctly when two members have the same value and result in an alias for the first entry. The PR [1985](https://github.com/GPflow/GPflow/pull/1985) has this issue since both `LIKELIHOODS_POSITIVE_MINIMUM` and `JITTER` have the value `1e-6`. 
As proposed by this PR, we simply stop making the wrapper an enum. This forces us to explicitly state the environment variable names alongside the default …
=> Don't use enums for default values

CONTRIBUTORS.md, RELEASE.md, gpflow/functions.py, tests/gpflow/test_functions.py
**Related issue(s)/PRs:** resolves #2091
* type check A
* throws error if the Parameter does not have the correct shape
* refer to https://github.com/GPflow/GPflow/issues/2091
=> fix bug of issue #2091 by type checking A

doc/sphinx/notebooks/getting_started/parameters_and_their_optimisation.pct.py
**PR type:**  doc improvement
Clarify statement about training_loss (which has confused someone in the past).
=> Clarify training_loss mention in tutorial
