GPflow/GPflow

GPflow/mean_functions.py, GPflow/param.py, testing/test_mean_functions.py
This is not functional (yet) but only serves as reference to #57 .
I introduce addition and multiplication for mean functions and provide two Polynomial mean functions to handle higher order combinations (linear * linear and combinations of polynomial with some other function).
@jameshensman I need a way to access the  parameters of the constituent mean functions (e.g. function1.A, function1.b etc.). I tried wrapping them into Parameterlists and running reduce(tf.add/tf.matmul) on them, but without any luck. Any other feedback would be highly appreciated!
=> Mean function Combination

README.md
... instead of GitHub. Fixes #69 .
=> Updates list of contributors and links to tensorflow.org

GPflow/kernels.py, GPflow/model.py, GPflow/param.py
This PR moves the autoflow functionality from the model class to the param class
This was movitated by the desire to compute the kernel matrix without constructing a model.
At the same time, the autoflow mechansim has been simplified: maintainance will hopefully be easier.
=> Universal autoflow

GPflow/param.py, testing/test_param.py
As per Alex's request, #94 
You can now do something like
```python
m = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern32(1))
m.fixed  # is False
m.kern.lengthscales.fixed = True  # works as before
m.kern.fixed = True
m.kern.lengthscales.fixed  # still True
m.kern.variance.fixed # now True
m.likelihood.fixed # still False
```
=> adding fixed property to parameterized

GPflow/kernels.py, testing/test_kerns.py
Kernels with active dimensions now select columns of data using
tensorflow's gather, rather that a packed series of scalar indexes.
old: `tf.pack([X[:,i] for in in active_dims])`
new: `tf.transpose(tf.gather(tf.transpose(X), active_dims))`
the latter is preferred because the graph is much smaller, especially
for a large number of active dimensions.
In addition, the kernel tests have been tidied and extended to cover
more of kernels.py.
=> Kern slicing

GPflow/transforms.py
We use log(1+e^x) to constrain parameters to be positive. tf has this function built-in as 'softplus', it seems sensible to use it.
=> using the built-in softplus function for simplicity

GPflow/param.py, testing/test_autoflow.py
A simplified mechanism to remove autoflow, less intrusive in other parts of the code, since only the `_needs_recompile` flag needs to be set to recompile the model and the AutoFlow functions.
=> Autokill autoflow

GPflow/hmc.py, GPflow/model.py, testing/test_hmc.py
Adding a simple boolean that returns the log-densities alongside the samples during HMC. these are useful for some diagnostics and model comparison (e.g. DIC).
=> Track logprobs

testing/test_autoflow.py, testing/test_conditionals.py, testing/test_hmc.py, testing/test_kerns.py, testing/test_likelihoods.py, testing/test_mean_functions.py, testing/test_method_equivalence.py, testing/test_methods.py, testing/test_model.py, testing/test_param.py, testing/test_predict.py, testing/test_priors.py, testing/test_transforms.py, testing/test_variational.py
- `reference` is now imported using `.reference`, which fixes a failure in Python 3
- All instances of `failUnless` and `failIf` are now replaced by `assertTrue` and `assertFalse`. The former are depreciated, and were giving me annoying warnings. Not too big a deal, but it would have needed to be changed eventually.
=> Get tests working with Python 3

GPflow/likelihoods.py, GPflow/transforms.py
A small fix to the `LowerTriangular` transform, so that it now also takes MxM matrices, rather than NxMxM arrays of matrices. This is sometimes required and just makes it a bit nicer to work with.
Additionally, in case of any questions about `likelihoods.py`, my IDE automatically enforces PEP8 style, which caused all the changes. I decided to add them anyway, but feel free to remove if you think it causes clutter.
=> LowerTriangularTransform now also takes matrix, not just array of matrices

GPflow/transforms.py
Small fix: we should use relative import where possible. importing 'from' GPflow inside GPflow could lead to circular dependence in the future.
=> removing potential for circular import

testing/test_custom_op.py
This fixes a minor issue where tensorflow spits out warnings along the lines of
```AssertionError: Nesting violated for default stack of <class 'weakref'> objects```
It turns out that this is because we were not closing interactive sessions during testing.
=> tearing down interactive session when finished

GPflow/param.py, testing/test_param.py
Currently, if a model has a prior *and* is fixed, we get an error, because the log_jacobian correction is requested for the fixed variable, and it hasn't been computed. 
This PR fixes that: now parameters with `fixed=True` and a prior will have a log_jacobian of 0. A regression test is included.
=> make sure log jacobian is computed even for fixed variables

setup.py
minor edits to setup.py. 
When building the user ops, we need to get the include directories for TensorFlow. Previously, we were doing this by calling python from within setup.py (!) which is problematic on some clusters. This fixes that.
=> improvements to setup.py

GPflow/kernels.py, testing/test_kerns.py
Linear and Polynomial kernels did not respect active_dims properly in Kdiag.
- Added slice call to Linear.Kdiag
- Fixed TestSlice to test more kernels.
- Fixed TestSlice to have the correct inputdim.
@jameshensman: I just want to double-check, I also think I fixed an existing bug in `TestSlice`, where all the `input_dim`s passed to the kernels was 1. Where actually, `input_dim` should be the number of inputs passed into the kernel, rather than the number actually used, right?
=> active_dims fix in Kdiag

GPflow/kernels.py
Deduces `input_dim` based on `input_dim` of a sub-kernel if a slice is used for `active_dims`, and the max of the `active_dims` otherwise.
=> Better deduction of `input_dim` for `kernels.Combination`

GPflow/kernels.py, GPflow/model.py, GPflow/param.py, GPflow/svgp.py, testing/test_autoflow.py, testing/test_data_object.py
Fixes #256 
#256 was caused by the changing of the graph behaviour. Now that all autoflow instances work on separate graphs, the `_tf_array` placeholders are overwritten each time an autoflow instance is created, because the placeholder must be on separate graphs. 
This broke the get_feed_dict mechanism, because sometimes the feed_dict contained placeholders that were outdated, i.e. on the wrong graph. 
The fix is to treat the `_tf_array` placeholders as temporary, and keep a reference to them inside AutoFlow (and in the model objective, which is really just a special case of AutoFlow). 
A regression test is included.
=> Autoflow fix

GPflow/sgpr.py, testing/test_method_equivalence.py
response to #280 
Turns out there was also an error in FITC . 
I modified the method equivalence test to have two identical columns of Y. When I tried generating different columns (and higher dimensional inputs) the tests (sometimes) failed at the current tolerances.
=> added test for multiple Y columns. Fix in SGPR and GPRFITC

GPflow/minibatch.py, GPflow/svgp.py, testing/test_methods.py, testing/test_minibatch_data.py
Fixes #284 
Includes regression test for #281 
This one will need squash merging, please.
I've pulled out a lot of the minibatch functionality, tidied it and added unit tests. I've also added a deterministic minibatcher that cycles through the data.
The cyclic minibatcher enabled me to give much more precise tests of the expected behaviour of SVGP. It could also be useful in general but the interface is not intuitive. I suggest we keep it as an expert feature.
=> Improve test coverage for stochastic gradients with tf optimizer.

GPflow/conditionals.py, GPflow/densities.py, GPflow/ekernels.py, GPflow/gplvm.py, GPflow/gpr.py, GPflow/kernels.py, GPflow/kullback_leiblers.py, GPflow/likelihoods.py, GPflow/mean_functions.py, GPflow/model.py, GPflow/quadrature.py, GPflow/sgpr.py, GPflow/tf_wraps.py, GPflow/vgp.py, testing/test_conditionals.py, testing/test_coregion.py, testing/test_ekerns.py, testing/test_transforms.py
This PR makes GPflow compatible with the next version of TensorFlow, where a few functions get renamed, and old deprecated ones are removed.
This is also compatible with the current version of TensorFlow, so it can be merged now.
=> Compatibility with next version of TensorFlow

GPflow/ekernels.py
As discussed in #327, the tiling operations in `ekernels.py` seem to be the main reason for the bad performance of LVMs on GPUs right now. This pull request avoids these tiling operations, but currently only for the RBF-kernel, so it is not ready to merge yet. It seems like the most important change is the one in `eKzxKxz`. For some toy data, the running time on GPUs reduced from `2s` to `25ms`.
You can comparre the traces before and after the change:
* [timeline_objective_lvm_cpu.json.gz](https://github.com/GPflow/GPflow/files/744540/timeline_objective_lvm_cpu.json.gz)
* [**timeline_objective_lvm_gpu.json.gz**](https://github.com/GPflow/GPflow/files/744541/timeline_objective_lvm_gpu.json.gz)
* [**timeline_objective_lvm_gpu_new.json.gz**](https://github.com/GPflow/GPflow/files/747623/timel …
=> Avoid copies via tiling in eKernels

doc/source/conf.py, docs_require.txt
Necessary because of rtd docs bug.
=> Requirements rtd

GPflow/param.py, testing/test_param.py
This change fixes a fix I pushed a couple of weeks ago.
The original fix was to make sure that we only have a single copy of a Param/ Paramterized object in the tree. It was a little overzealous and wouldn't allow us to do something like:
```
m = GPflow.param.Parameterized()
p = GPflow.param.Parameterized()
m.foo = p
m.foo = p  # raise exception here
```
This commit fixes the issue.
=> Allow reassignment of Param(eterized)s

GPflow/param.py, testing/test_param.py
Hi everyone!
While trying out the convenient new randomization-feature contributed by @Bonnevie, I found a small bug: Multidimensional Params are flattened when randomized without a prior. The with-prior-case seems to work fine.
An example: The Param `x = Param(np.ones(size=(3, 3)))` with shape `x.shape == (3, 3)` would be of shape `x.shape == (9,)` after calling `x.randomize()`.
This pull request seems to fix the issue and makes the relevant test more specific in order to catch the problem. Care to have a look, @Bonnevie?
=> Fix randomize for multidimensional Params without priors

GPflow/model.py, GPflow/param.py, testing/test_pickle.py
In the current master, it is not possible to pickle a model which has been loaded from a pickle itself, i.e. the operation `dumps(loads(dumps(model)))` fails. The problem is that a freshly unpickled and untouched model does not have `_tf_array`s for all Param objects und the corresponding `__getstate__`-method tries to remove it resulting in an exception.
There is a fix for this in in `model.py` which ensures that things like `model._graph` are only removed when they actually exist. This PR does the same in the `Param`-class which seems to fix the issue.
=> Fix pickle idempotence

GPflow/transforms.py, testing/test_transforms.py
Following the discussion in GPflow/GPflowOpt#17 this implements a backward/forward transform which should avoid overflows and divisions by zero. Also adds tests to verify the warnings are no longer popping up.
=> Robust numpy softplus

GPflow/gpmc.py, GPflow/gpr.py, GPflow/model.py, GPflow/sgpmc.py, GPflow/sgpr.py, GPflow/svgp.py, GPflow/vgp.py, testing/test_model.py
As reported in #454 , the Zero mean function as default argument in the constructor of the 6 models results in recompilations when new model instances are created. This should solve this, also added a regression test.
=> Avoid recompilation when creating new model instances

README.md
The readme is a bit unclear on the TF version (see #479). The updated one indicates that we support at least tf1.0 and that we aim to support the latest version.
=> Clarify TF version

GPflow/gplvm.py
The GPLVM code was failing when specifying 
float_type = float32
in settings.
Small fix use the correct type as is done in Param.
Testing question: Are we testing the tf.float32 scenario?
=> Fix GPLVM for GPU/float32

README.md, doc/source/intro.rst, setup.py
Following #487 , removal of the TF import in setup.py. This allows single-command installation in clean environments, without first installing TF. I also updated the installation instructions in the documentation and readme.
=> Remove TF import in setup.py

gpflow/_version.py
Version in `_version.py` was inconsistent with that mentioned in `RELEASE.md`.
=> Version was inconsistent with RELEASE.md

gpflow/models/svgp.py
This tiny PR allows the user to pass num_data as an optional argument to the SVGP class. this is helpful when the X, Y pair are not numpy arrays, so we cannot get the num_data from them.
=> Gpflow 1.0 svgp args

gpflow/core/node.py
If `parent` (L115) has `__len__()` defined, this will be called in the `if` statement. This is not the intended check.
I think in this instance it's better to be explicit, as we do really want to check for `None`. Some objects may have a `__len__()` method defined. In my case, this relies on parameters which are set in the constructor, which are not initialised at the time that `if parent` is run.
=> Explicit checking of None in set_parent

.travis.yml, codecov.yml, gpflow/misc.py, gpflow/params/dataholders.py, gpflow/params/parameter.py, gpflow/params/parameterized.py, gpflow/params/paramlist.py, gpflow/test_util.py, gpflow/training/tensorflow_optimizer.py, setup.py, tests/test_core.py, tests/test_dataholders.py, tests/test_notebooks.py, tests/test_optimizers.py, tests/test_param.py
This PR major aim is an increasing the test coverage. Previously, `codecov` **was configured to calculate coverage score for both python folders**: `gpflow` and `tests`. This is a little bit unfair as we are really interested only in `gpflow` package. Because `tests` directory was included into `codecov` reports, the scores were skewed towards 100% a bit. When I turned off coverage for `tests` the score dropped from `97%` to `94.7%`, so I managed to push it back to `97.31%`.
Additionally, I removed `miniconda` installation, switched tensorflow version to 1.4 and turned on caching in travis builds - as a result installation takes twice less time then before.
@alexggmatthews, @jameshensman, @markvdw
=> Increase test coverage.

gpflow/models/svgp.py, tests/test_model.py
A very bad bug in SVGP, which had the minibatches out of sync (they were given different initial seeds). The fix is a oneliner, and this adds a regression test as well.
=> Fixed SVGP minibatch issue, plus regression test

gpflow/test_util.py, tests/test_ekerns.py
* Created session_context monster (decorator / context manager) for pytests.
* Using distinct graphs and sessions per test case made quadrature tests a bit faster.
* Removed code duplication.
=> Speed up some ekernels test on 40%.

gpflow/misc.py, gpflow/params/dataholders.py, tests/test_model.py
Until https://github.com/tensorflow/tensorflow/issues/14633 is resolved, Minibatch should be kept from `auto-initializing` feature. Simple cases are not affected. Only when you switch between sessions you will have to re-initialize Minibatch explicitly.
=> Exclusive behaviour for Minibatch

gpflow/conditionals.py, gpflow/kullback_leiblers.py, gpflow/models/svgp.py, gpflow/models/vgp.py, gpflow/transforms.py, tests/test_conditionals.py, tests/test_kldiv.py, tests/test_method_equivalence.py, tests/test_methods.py, tests/test_transforms.py, tests/test_uncertain_conditional.py, tests/test_variational.py
As discussed in #610, this PR makes `q_sqrt` D x M x M. This was long overdue, and pulls `q_sqrt` in line with the TensorFlow convention of how to represent lists of matrices.
=> `q_sqrt` is now D x M x M.

gpflow/misc.py
`df.reindex_axis()` in `pretty_pandas_table` is now deprecated in pandas and can be avoided anyway.
=> remove reindex_axis call in pretty_pandas_table

gpflow/models/gplvm.py
`np.linalg.eigh` (see [documentation](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linalg.eigh.html)) returns the eigenvalues and eigenvectors in ascending order. The sorting was therefore redundant. Also, `evecs`  and `evals` were flipped. This PR fixes both problems.
=> Corrected the PCA implementation

gpflow/_settings.py, gpflow/kernels.py, tests/test_kerns.py
- renames square_dist and euclid_dist to scaled_square_dist and scaled_euclid_dist to be more consistent about what they actually return, and adds docstrings
- adds SquaredExponential as alias to RBF
- adds RationalQuadratic kernel
- includes a test for Rational Quadratic (\alpha->\infty) -> Squared Exponential
=> Adds rational-quadratic kernel and minor clean-up of notation

gpflow/transforms.py, tests/test_transforms.py
The free vector for the lower triangular transform wasn't being handled consistently. This PR makes the free state a vector of length `num_matrices * triangle_num`. A test ensures that the numpy and tensorflow transforms agree
=> fix consistency of triangular transform

gpflow/core/compilable.py, gpflow/decors.py
- makes sure that the AutoBuild metaclass does not overwrite the `__init__`'s docstring anymore
- makes the naming of the functions inside the decorators more consistent
- improves the name_scope() docstring
=> Minor improvement to decorators and AutoBuild

gpflow/densities.py, tests/test_densities.py
tf.cond breaks things when the shapes are unknown, make `multivariate_normal` require column vectors or matrices (i.e. 2D input) and raise a warning when the shape is unknown or less than 2D
=> remove conditional shape changes from multivariate_normal

gpflow/expectations.py, tests/test_expectations.py
This pull request fixes two issues:
- the signature `(Gaussian, identity_mean, None, kernel, features)` was calling itself whenever no specific implementation for `kernel` exists because `Identity` is a type of `Linear` mean function
- the default number of Hermite points (often too high) was used for nested calling of `expectation` as the `num_gauss_hermite_points` argument was not being passed beyond the first call
What is irking about the current fix for the second issue:
- `_expectation`'s should, in theory, have no knowledge of Hermite points and should not receive them as arguments
- the code is now slightly more verbose, though at least explicit
- to keep the code and signatures simple (and not changing 35 of them) the number of Hermite points argument (`nghp`) is not checked by …
=> expectations: pass num hermite points to _expectation() and minor cleaning

gpflow/likelihoods.py
added name argument to `class Gaussian(Likelihood)`, this prevented storing and loading models to and from files. I am pretty sure that there are more of the same, but I am not familiar enough with the code base to point them out. See #689.
=> name gaussian likelihoods

.travis.yml, gpflow/training/tensorflow_optimizer.py, setup.py
Hello all!
Current GPflow is broken for tensorflow >= 1.6. This is very sad as TensorFlow has advanced to 1.7 version. The issue was caused by uninitialized variables error:
```
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value beta1_power
[[Node: beta1_power/read = Identity[T=DT_FLOAT, _class=["loc:@RBF-d9f4a003-0/lengthscales/unconstrained"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](beta1_power)]]
```
To reproduce the error you can install GPflow master with tensorflow >= 1.6 and run this MWE:
```
...: import warnings
...: import numpy as np
...: import tensorflow as tf
...: import gpflow as gp
...:
...: np.random.seed(0)
...:
...: N, D = 100, 2
...: M = 10
...: X = np.random.uniform(size=(N, D))
...: Y = np.sin(10 * X)
...: Z = …
```
=> Optimizers incompatibility with TensorFlow >= 1.6

gpflow/training/scipy_optimizer.py, tests/test_gplvm.py, tests/test_optimizers.py
Hello all,
There is a bug in current ScipyOptimizer. It doesn't pass options dictionary to actual scipy optimizer. You can check new test for a failure case.
w/o this fix, master will ignore `gtol` option:
```
o1 = gpflow.train.ScipyOptimizer(options={'gtol': gtol_value})
```
=> GPflow ScipyOptimizer passes options to actual ScipyOptimizer incorrectly

gpflow/params/parameter.py, tests/test_param.py
Currently, as_pandas_table() added the values of parameters as *references*; i.e., when updating the model, all previously generated tables would change. I think the key reason for using as_pandas_table() is to obtain a static copy of the parameters (e.g. to compare how they changed as the model is updated). This PR fixes that by adding a .copy().
MWE: `test_as_pandas_table_static()` fails without 7720633, passes afterwards.
=> as_pandas_table: copy value before adding to DataFrame

gpflow/kullback_leiblers.py, tests/test_kldiv.py
Also added a test to prevent future regressions.
This addresses the bug in both #734 and #725  .
=> Fixed `gauss_kl` when the shape of the Gaussian parameters is unknown

README.md
* [Title] Change readthedocs to point at master
* [Description] the link to the docs from the readme page should point at the master version of the docs
* [Minimal working example] n/a
=> updating readthedocs link in readme to point at master

gpflow/_settings.py, gpflow/gpflowrc, tests/test_config.py
Recently, we needed to inform a user about specific functions being called inside GPflow.
For example, in the expectations framework when quadrature is used and in the multi-output framework to indicate which conditional is used.
We did this using simple print-statements, but this isn't a good practice.
This PR adds a standard Python `logger` to GPflow which can be used for these use-cases.
```python
from gpflow import settings
logger = settings.logger()
...
logger.debug("Quadrature is used to calculate the kernel expectation for Matern-1/2")
...
```
The debugging level `(CRITICAL, WARNING, INFO, etc.)` is set in the RC-file and can be changed to a one's needs.
=> Add logger to settings

gpflow/saver/coders.py
The model `gpflow/saver/coder.py` makes use of the private API for the `typing` module, and due to internal changes the current code does not support Python 3.5.2 (the default python3 for Ubuntu 16.04 LTS). This change adds support for the private API for Python 3.5.2 as well as Python 3.5.3+
=> Support Python 3.5.2 in typing checks (Ubuntu 16.04 default python3)

.travis.yml, tests/test_saver.py
The current unit tests failed under TensorFlow 1.8. This PR fixes this and makes GPFlow compatible with the latest TensorFlow release. @awav @markvdw on travis TF1.6 is still used, shouldn't we switch to the latest version?
- TensorFlow 1.8
- Python **3.6.5**
=> Fix failing unittest under TensorFlow 1.8

gpflow/training/natgrad_optimizer.py, gpflow/training/optimizer.py, gpflow/training/scipy_optimizer.py, gpflow/training/tensorflow_optimizer.py
Hello everyone,
Reasons for this PR:
- `step_callback` docstring states that optimizer doesn't pass arguments to the function and function can have as many arguments as user wants including nil arguments, but an optimizer pass results of `session.run` operation to the `step_callback`, therefore causes failures. [update] Function must be with signature `fun(*args, **kwargs)`, but it is still confusing that nothing is passed into callback.
- Optimizer minimize returns tensorflow operation, which after running this tf.Operation though `session.run` returns `None`.
- It would be nice to expose step number to callback explicitly.
Thanks!
=> Optimizer's callback accept step number.

gpflow/quadrature.py
The current implementation of `ndiag_mc` didn't handle multi-dimensional kwargs `Ys` and failed accordingly. This hotfix-PR resolves the problem.
This minimal example shows a possible use-case
```python
import tensorflow as tf
from gpflow.quadrature import ndiag_mc
N = 10
X_dim = 2
Z_dim = 2
Y_dim = 4
def func(Z, X=None, Y=None):
XZ = tf.concat([X, Z], axis=1)  # N x (X_dim + Z_dim)
return tf.reduce_sum(XZ - Y, axis=1)  # N x 1
Z_mu = tf.zeros((N, Z_dim), dtype=tf.float64)
Z_var = tf.ones((N, Z_dim), dtype=tf.float64)
X = tf.random_normal((N, X_dim), dtype=tf.float64)
Y = tf.random_normal((N, Y_dim), dtype=tf.float64)
Ez = ndiag_mc(func, 1000, Z_mu, Z_var, logspace=False, X=X, Y=Y)
print(tf.Session().run(Ez))
```
With the current implementation this fails:
```
ValueError: Dimension 0 in …
```
=> Fix bug in ndiag_mc re multi-dimensional kwargs

gpflow/params/parameter.py, gpflow/params/parameterized.py
```python
sm = gpflow.models.SVGP(np.array([[1.0]]), np.array([[1.0]]), gpflow.kernels.RBF(1),
gpflow.likelihoods.Gaussian(), np.array([[1.0]]),
q_diag=False, whiten=False, minibatch_size=None)
sm.trainable = False  # does not work
sm.set_trainable(False)  # does work
```
The reason was that while in Parameterized, trainable was a property, this was not the case in Parameter. This is fixed by this PR.
Also, there was code duplication in Parameterized between trainable.setter and set_trainable(); in this PR, trainable.setter simply calls set_trainable.
=> Parameter.trainable was not properly a property and Parameterized.trainable did not special-case DataHolders

gpflow/_settings.py, tests/test_likelihoods.py
Now that we are no longer supporting python2, the references to the six module are no longer necessary.
=> remove references to six module

gpflow/likelihoods.py
Hi all,
There is a bug in the current gpflow code re the saving and loading of models. 
The bug only occurs when the model has a softmax likelihood.
```python
import numpy as np
import gpflow
N, Nc = 20, 10
X = np.random.randn(N, 5)
Y = np.random.randint(Nc, size=(N, 1))
like = gpflow.likelihoods.SoftMax(Nc)
kern = gpflow.kernels.RBF(5)
m = gpflow.models.SVGP(X, Y, kern, likelihood=like, Z=X.copy(), num_latent=Nc)
gpflow.Saver().save("model.gpf", m)
```
Close the session and reopen a new one
```python
import gpflow
m = gpflow.Saver().load("model.gpf")  # CRASHES
```
This breaks with:
```
Input 'y' of 'Equal' Op has type int64 that does not match type int32 of argument 'x'
```
The problem is that the type of tf.shape and self.num_classes in the softmax likelihood is different and as a …
=> Bugfix control dependencie in likelihoods

README.md
I implemented the deep arcosine kernel in the code that accompanies this paper using GPflow:
https://arxiv.org/abs/1804.11271
I've added a link to the README of the project. 
Particular effort has gone into numerical stability, which allowed us to backpropagate. 
The code uses an old version of GPflow, has only basic unit test framework and would probably benefit from an option to use multiple parameters. That said it is still useful to link it in my opinion.
=> Adding widedeepnetworks repository link

gpflow/conditionals.py, gpflow/expectations.py, gpflow/kernels.py
Some stationary kernels are based on the squared radial distance, others need the radial distance itself. This allows both to be implemented as naturally as possible while avoiding the inefficiency of square(sqrt(r2)).
=> Separate K_r and K_r2 for stationary kernels

gpflow/conditionals.py, gpflow/expectations.py, gpflow/kernels.py, gpflow/likelihoods.py
Stationary kernels only depend on the distance r between x and x'; hence instead of duplicating the distance calculation in each child class of `Stationary` it would make more sense to simply define their implementation through k(r).
=> Cleaning up stationary kernel implementations

doc/source/notebooks/multioutput.ipynb, gpflow/multioutput/conditionals.py, gpflow/multioutput/features.py, tests/test_multioutput.py
* [Title](#title)
* [Minimal working example](#minimal-working-example)
This provides the missing MixedKernelSeparateMof that does efficient  mixing of ind. latents for separate inducing points.
Working on the solution to #819 I found that one way to address the problem was to define the missing feature MixedKernelSeparateMof and to create the corresponding dispatch route. Bug #819 is still not resolved because the path `conditional(feat: SeparateIndependentMof, kern: SeparateMixedMok)` has a shape conflict, however this PR will add a more efficient route anyways.
See the commited `notebooks/multioutput.ipynb`
Not a significant code change
=> Added MixedKernelSeparateMof

gpflow/params/parameterized.py
This should be for abstract methods only. It also causes the inspections in my IDE to constantly say that I need to implement more abstract methods...
=> We should not be using NotImplementedError for `.fixed`.

gpflow/models/model.py, gpflow/models/sgpmc.py, gpflow/models/vgp.py
Some docstrings had `\\` for LaTeX maths commands but had a `r` at the start, so they were escaped too much. One docstring was missing the `r` but had some single-`\`. Fixed by this PR.
=> fix models maths documentation

gpflow/models/model.py, gpflow/models/sgpmc.py, gpflow/models/vgp.py
Some docstrings had \\ for LaTeX maths commands but had a r at the start, so they were escaped too much. One docstring was missing the r but had some single-\. Fixes those.
=> fix models maths documentation (#905)

gpflow/gpflowrc
(inhouse version of PR #903)
The available Python logging levels are as written now in the file:
https://docs.python.org/3/library/logging.html#levels
I don't think it's worth making a test for this. You can check the bug by doing:
```python
import gpflow
gpflow.settings.logging.level = 'NOSET'
gpflow.settings.logger()
```
and
```python
import gpflow
gpflow.settings.logging.level = 'NOTSET'
gpflow.settings.logger()
```
=> Typo "NOSET" -> "NOTSET" in gpflowrc

gpflow/kullback_leiblers.py, tests/test_kldiv.py
This PR adds the ability to pass the Cholesky of K to `gauss_kl(.)` for the unwhitened case, instead of `K`. It prevents the double cost of inverting `K` twice, in both conditionals and gauss_kl.
- added `K_cholesky` kwarg to `kullback_leiblers.gauss_kl`
- updated file to the new way of documenting array shapes. From `A x B` to `[A, B]`
- added unit test
=> Minor performance improvement: pass Cholesky of K to gauss_kl

Dockerfile, gpflow/training/tensorflow_optimizer.py
This fixes issue https://github.com/GPflow/GPflow/issues/995 and makes GPflow compatible with the latest TF version 1.14.
Details:
TensorFlow wrapped `tf.train` in a module deprecation-wrapper, so we simply go and get the items from inside the wrapper.
=> GPflow TF 1.14 compatible. Fixes optimizers importing issue.

contributing.md
Correct error in python example in contributing documentation.
**bug fix** Example in contributing.md refers to `self`, which is not defined for a class method.
=> fix error in python example in contributing readme

gpflow/training/scipy_optimizer.py
#1011 introduced an f"" string that's incompatible with python 3.5, as noted in #1056. This returns python 3.5 compatibility by using an explicit "".format() call.
=> Return compatibility with python 3.5

gpflow/kullback_leiblers.py, gpflow/models/gplvm.py, gpflow/models/sgpmc.py, gpflow/models/sgpr.py, gpflow/models/svgp.py, gpflow/models/util.py, notebooks2/advanced/convolutional.ipynb, notebooks2/advanced/multioutput.ipynb, notebooks2/basics/gplvm.ipynb, notebooks2/intro_to_gpflow2.ipynb, tests/test_features.py, tests/test_gplvm.py, tests/test_likelihoods.py, tests/test_mean_functions.py, tests/test_method_equivalence.py, tests/test_methods.py, tests/test_multioutput.py, tests/test_multioutput_features.py, tests/test_predict.py, tests/test_printing.py, tests/test_training.py, tests/test_uncertain_conditional.py, tests/test_variational.py
This change makes it easier to distinguish the module `inducing_variables` from the model attribute `inducing_variable`, and is in line with the nomenclature for the other object - we generally think of a single \vec{u} just as we think of a single k(.,.)
=> Rename inducing_variables -> inducing_variable as model attribute

tests/test_notebooks.py
Forgot to remove it from the blacklist in #1076.
=> Quickfix: enable notebook test of regression.ipynb

gpflow/base.py, tests/test_prior.py
When doing MLE instead of MAP (i.e., no prior on the hyperparameters), the objective should be independent of the parametrisation of the parameters. This means that the `log_prior` of a parameter with a `transform` (e.g. `positive()`) but without a `prior` should be zero. This was not the case, leading to difficult / wrong optimisation e.g. in #1087. Fixed in this PR.
=> fix bug in log_prior when a Parameter has a transform but no prior

gpflow/base.py, tests/test_printing.py
This supercedes PR #1100 
The variables and trainable_variables parameters on tf.Module return tuples: see [here](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/module/module.py#L143) However, the key problem here is that at the moment the `Module` wrapper we have neither returns lists nor tuples, but rather a generator for `self._flatten`. If you don't wrap the generator in an iterable, when you pass the generator to the frozenset SampleHelper, the generator exhausts after its first use. eg:
```
params = m.trainable_parameters
y = [p for p in params]  # List[Params]
z = [p for p in params]  # [] Empty! 
```
I was unsure where to put the tests, so I put them in printing.
=> gpflow.Module.parameter (base for Model) returns an tuple, not generator 

gpflow/config/__config__.py, gpflow/likelihoods/robustmax.py, gpflow/models/gpmc.py, gpflow/models/sgpmc.py, tests/test_config.py, tests/test_prior.py
This PR supercedes PR # 1100
TF Probabilities does not allow you to either choose a dtype for your distributions (see PR #1100 ) at the moment. Instead it is currently inferred by the dtype of the params. Tensorflow also has no way of setting default dtypes in the backend, and this is also an open issue.
There are two solutions to this: 
* One is simply to covert native values to the default dtype before sending them into the tfp distribution. This relies on the user knowing this is how tfp distributions work.
* The other is to create an intermediate wrapper around all the distributions in tfp, and allow users of gpflow not to have to worry about this.
Although the first is uglier (users will get bitten by this, possibly), if we create a wrapper around tfp.distributions.Gamma etc, we will …
=> Ensure all tf_probability distributions take the correct dtype parameters

gpflow/optimizers/scipy.py
Changes behaviour of `step_callback` so that the callback only gets called once per optimisation step, not once per objective function evaluation. Makes gpflow2's Scipy() behave more like gpflow1's ScipyOptimizer()/monitoring.
=> Change step_callback behaviour of Scipy optimizer in gpflow2 to behave as in gpflow1

doc/source/notebooks/advanced/convolutional.ipynb
A previous PR left the `convolutional.ipynb` in an invalid state (Jupyter throws an error). (PR #1108). This directly undoes that and has been manually tested.
=> Fix convolutional notebook (currently in invalid state for jupyter)

gpflow/models/gplvm.py, gpflow/models/vgp.py
Missing `full_output_cov` parameter prevents us from calling `predict_f_samples` from the base class. Crash occurs.
=> Small fixup for GPLVM and VGP.

gpflow/config/__config__.py, gpflow/utilities/bijectors.py, gpflow/utilities/utilities.py, tests/test_config.py, tests/test_printing.py, tests/test_utilities.py
Based on @awav's second TODO list item in #1144: _"Current positive transform uses softplus, but in some cases it is "preferable" to use exp instead; it would be nice to have an option in the gpflow.config, such that the user could choose global positive transformation"_
Still a work in progress but putting it up here for early feedback (as I calibrate coding style for this project).
=> Add config option for positive bijector + re-introduce positive lower bound

gpflow/likelihoods/likelihoods.py
For an easier transition from v1, and improved stability during optimisation, this sets a lower bound on the likelihood variance. 
Compared to imposing the lower bound within the positive transform, this is (a) more transparent to the user and (b) does not impose the restriction on other Parameters.
=> Assign lower bound directly to likelihood variance.

gpflow/optimizers/scipy.py, tests/test_optimizers.py
As the Scipy optimizer combines numpy with tensorflow, we can't simply wrap its `minimize()` method in `tf.function()`. Instead, this PR adds a `jit` flag (True by default) which wraps the evaluation of objective and its gradients in `tf.function()`.
=> Add jit flag to gpflow.optimizers.Scipy

gpflow/base.py
1. Adds `is_tensor_like` property to `Parameter` to ensure compatibility with TensorFlow 2.1
2. Adds explanation to `Parameter._should_act_as_resource_variable`
3. Clarify in repr(Parameter()) that it is a gpflow.Parameter, not a tf.Tensor. Changes `gpflow.Parameter.__repr__` to identify itself as a gpflow object to ease debugging.
Examples:
- `gpflow.Parameter(1.0, transform=gpflow.utilities.positive(), name="variance")`:
```
<gpflow.Parameter 'Variable:0' dtype=float64 unconstrained shape=() unconstrained numpy=0.5413248546129181 constrained shape=() constrained numpy=1.0>
```
- `gpflow.Parameter(np.eye(3), transform=gpflow.utilities.triangular())`:
```
<gpflow.Parameter 'Variable:0' dtype=float64 unconstrained shape=(6,) unconstrained numpy=[1. 0. 0. 1. 1. 0.] constrained shape=(3, 3) …
```
=> TensorFlow 2.1 compatibility, and identify as gpflow.Parameter in repr() to ease debugging

gpflow/likelihoods/robustmax.py, tests/test_likelihoods.py
`test_likelihoods.py` had *all* MultiClass tests blanket-skipped as there was a bug (#1091). This PR cleans up the situation as follows:
- one test was actually passing - now unskipped.
- one test was made to pass by reducing the `_squash` attribute in the RobustMax class from 1e-4 to 1e-6.
- the other tests are now skipped individually.
(The failing tests are actually due to an issue in `ndiagquad` that can't seem to handle the integration over several latent GPs correctly as is required for the MultiClass case)
=> Improve previously skipped MultiClass tests

gpflow/base.py, tests/test_base.py, tests/test_features.py
In GPflow2, `Parameter` behaves differently from GPflow1, as noted in #1197.
Specifically, when using a positive transform, initializing or assigning the value 0.0 is perfectly fine in the forward pass: `p = gpflow.Parameter(0.0, transform=gpflow.utilities.positive())`, and it looks like nothing is wrong; the constrained representation is 0.0 as expected. (In GPflow1, it would implicitly force the value to be the lower bound of 1e-6.) However, the *unconstrained* representation is then `-inf`, which leads to `nan`s when computing gradients in the backward pass. This is error-prone and hard to debug. To make this issue more obvious, this PR adds an error check.
=> Add validation to Parameter.assign() to increase robustness of transforms

gpflow/base.py, tests/test_base.py
TensorFlow's tf.cast(value, dtype) implicitly does a tf.convert_to_tensor(value)
*before* the cast when the value is not a tensor already. When value is a python float,
this results in the following behaviour:
```python
>>> tf.cast(0.2, tf.float64)
<tf.Tensor: id=37, shape=(), dtype=float64, numpy=0.20000000298023224>
```
instead of the expected expansion of 0.2 to float64 precision that you get when
passing in an object that already carries dtype information, such as a numpy array
(which has float64 precision by default):
```python
>>> tf.cast(np.array(0.2), tf.float64)
<tf.Tensor: id=40, shape=(), dtype=float64, numpy=0.2>
```
This affected *all* gpflow.Parameter objects, resulting in numerical discrepancies
between GPflow 1 and 2, due to the pass through _cast_to_dtype, which is fixed …
=> Fix issue with tf.cast() and implicit dtype conversion

.coveragerc, gpflow/__init__.py, gpflow/base.py, gpflow/inducing_variables/inducing_variables.py, gpflow/kernels/base.py, gpflow/likelihoods/likelihoods.py, gpflow/likelihoods/robustmax.py, gpflow/mean_functions.py, gpflow/utilities/utilities.py
Makes all GPflow objects (kernels, likelihoods, ...) inherit from `gpflow.base.Module` (not `tf.Module`), and adds `_repr_html_` and `_repr_pretty_` methods to `gpflow.base.Module` that return appropriate rich representation for jupyter notebook and IPython shell, respectively.
=> Improve pretty-printing of GPflow objects in IPython shell and jupyter notebook

doc/source/notebooks/tailor/gp_nn.ipynb, gpflow/kernels/base.py, gpflow/kernels/changepoints.py, gpflow/kernels/linears.py, gpflow/kernels/misc.py, gpflow/kernels/mo_kernels.py, gpflow/kernels/periodic.py, gpflow/kernels/statics.py, gpflow/kernels/stationaries.py, tests/test_kernels.py
In GPflow 1, each kernel's `K` and `K_diag` method was supposed to take a `presliced` argument. Not all kernels actually had this signature, and not all kernels who had this signature actually did anything with the argument. This PR makes `presliced` an argument solely to the kernel's `__call__`, with the intent of making the entire set-up a lot cleaner.
=> Clean up `presliced` argument to kernel calls

gpflow/base.py
`Parameter.__repr__` called `.numpy()` on the constrained and unconstrained representations - this throws an error when in graph mode (tf.function-wrapped), which can lead to errors-in-exception-handling, so this PR makes use of `tf.eagerly_executing()` to check whether we are in graph mode, and if so, only print shapes and dtype, not values.
=> fix Parameter.__repr__ for tf.function mode

MANIFEST.in, gpflow/py.typed
* [Title](#title)
* [Minimal working example](#minimal-working-example)
Ship GPflow with type information
The latest GPflow2 release candidate has a lot of type hints. This is great, we love type hints!
Unfortunately, GPflow consumers (that is, anyone creating a new repo with modules containing something along the lines of `import gpflow`) will not be able to use MyPy to check they're consuming GPflow objects correctly. This is due to [how MyPy locates type hints](https://mypy.readthedocs.io/en/stable/running_mypy.html#how-mypy-handles-imports). See the section below for an example.
This PR ensures that whenever GPflow is installed via `pip`, users will be able to get type hints for GPflow objects.
Create a standalone Python script with the following lines …
=> Ship type information as specified by PEP 561

gpflow/conditionals/util.py, tests/test_conditionals.py, tests/test_kldiv.py
Problem:
* KL divergence calculations only take lower triangle parts of q_sqrt in
their calculation (implying a lower triangular parameterisation of
covariance)
* Conditional calculations perform calculations using the whole of
q_sqrt.
* The end result is if you forgot to add the triangular transform
to the q_sqrt, your forward pass may be the same (if you initialise with
a triangular matrix), but your gradients will immediately stop q_sqrt
being triangular.
Fix:
* Conditional calulcations now only take the lower triangle parts of q_sqrt
in their calculation
=> Inconisistency on whether q_sqrt is triangular fixed.

doc/source/conf.py
* Include special methods in docs
* Implements #1039. With this change, all special methods _and_ functions, not only `__init__` will be included in the docs
* For an MWE, build the docs and look at the Coregion kernel docs
=> include special methods in docstrings

README.md, doc/source/notebooks/gpflow_2_upgrade/gpflow2_upgrade_guide.ipynb, gpflow/kernels/base.py, gpflow/kernels/periodic.py, gpflow/kernels/stationaries.py, gpflow/utilities/ops.py, tests/test_kernels.py
Addresses unclear/insufficient documentation (closes #1230).
Previously, `Periodic` did not take `active_dims`, and only the first code example in #1230 would have worked - but the `Kernel` base class specifies `active_dims` as part of the interface, so this PR adds getter/setter that pass through to the `base` kernel, as well as accepting `active_dims` in the `Periodic()` constructor but raising an error when it is not consistent with `base.active_dims`.
=> Improve documentation and behaviour of Periodic kernel

README.md
We've created `kerndisc` for time series modeling using health related data. This PR aims to add it to the GPflow projects section, as we hope that it might be useful to others.
Summary: `kerndisc` is a library for automated kernel structure discovery in univariate data. It aims to find the best composition of kernels in order to represent a time series. `kerndisc` currently possesses a test coverage of over 90 %. Still, there is no claim to correctness, contribution and correction is heavily desired.
Usage: [See here for an example.](https://github.com/BracketJohn/kernDisc#usage)
=> Add `kerndisc` to projects section

gpflow/utilities/utilities.py
* [Preserve types in deepcopy_components](#title)
* [Minimal working example](#minimal-working-example)
Bug fix: type information was lost in deepcopy
The following would fail before this fix, as the type information isn't preserved
```python3
import tensorflow as tf
from gpflow.utilities import deepcopy_components
class Mod(tf.Module):
pass
mod: Mod = deepcopy_components(Mod())
```
=> preserve types in deepcopy

gpflow/models/__init__.py, gpflow/models/sgpr.py
`gpflow.models.sgpr` contains two sparse GP models, SGPR and GPRFITC. They had a common subclass to provide the upper_bound() method. They also have the same `__init__`, which is unified in this PR.
=> clean up SGPR common __init__

doc/source/notebooks/gpflow2_upgrade/gpflow2_upgrade_guide.md
The wrong heading levels were messing up the table of contents in readthedocs. This should also get the images back into the rendered notebook, which fixes #1286.
=> fix gpflow2_upgrade_guide notebook heading levels and images

.circleci/config.yml, doc/source/notebooks/advanced/convolutional.pct.py
Speed up convolutional notebook so that jupytext doesn't timeout on circleci. Fixes #1300
=> Quickfix: speedup convolutional notebook

doc/source/notebooks/gpflow2_upgrade/gpflow2_upgrade_guide.md
Apparently sphinx breaks on underscores in the image embedding, e.g. `![scipy_optimizer](scipy_optimizer.png)` would not actually render the image. This PR adds proper alt texts.
=> fix more images in the gpflow2 upgrade guide

gpflow/conditionals/conditionals.py, gpflow/kernels/base.py, gpflow/kernels/linears.py, gpflow/kernels/statics.py, gpflow/utilities/ops.py, tests/gpflow/conditionals/test_broadcasted_conditionals.py, tests/gpflow/conditionals/test_conditionals.py, tests/gpflow/conditionals/test_util.py, tests/gpflow/kernels/test_broadcasting.py
Hi all,
Reintroduce broadcasting functionality we had in GPflow 1 (added in #895) back into GPflow 2.  
This PR generalises gpflow's conditional code to work with tensors that have an arbitrary number of leading dimension. Before we assumed that `Xnew` passed in `gpflow.conditional` was a two-dimensional tensor, typically referred to as `[N, D]`. This PR makes it possible to pass in `Xnew` tensors of shape `[..., N, D]`, where `[...]` can be any leading dimensions. The changes required for this are minor:
1) A couple of `tf.matmul`'s are replaced with `tf.tensordot`'s.
2) `kernels.K(X1, X2)` returns the kernel evaluated on every pair in `X1` and `X2`. This is the same behaviour as before, but now tensors with leading dims are supported. 
E.g. if `X1` is `[N1, S1, D]` and `X2: [N2, S2, …
=> Broadcasting of kernels reintroduced

Makefile, tests_requirements.txt
To make it easier for contributors to get their PR branches conforming to the format checker.
Also cleans up the .PHONY and test targets.
=> Update Makefile: add 'make format'

gpflow/conditionals/sample_conditionals.py, gpflow/models/model.py, gpflow/utilities/ops.py, tests/gpflow/models/test_model_predict.py
`model.predict_f_samples` was broken: it did not work for `full_cov` equals `False`. This PR fixes this and adds a test. The code reuses `sample_mvn` which also makes more sense.
=> Fix predict_f_samples

setup.py
Hi,
This could fix #1348 as:
- gast is only added as a requirement if tensorflow is not already installed;
- we read check what's the latest available version of tensorflow on pypi and pin a version of gast accordingly.
Make sense?
Best Regards,
Marco
=> gast dependency

gpflow/ci_utils.py, tests/gpflow/kernels/test_broadcasting.py, tests/gpflow/likelihoods/test_likelihoods.py
There is a test in test_likelihoods that checks whether we missed any likelihood in the test - this is so we are reminded to add tests when we add new likelihoods! But the test was broken, and this PR fixes the test. I've also done the same for the kernel broadcasting test.
=> Fix "comprehensiveness" tests

README.md, doc/source/intro.rst, doc/source/notebooks/advanced/multioutput.pct.py
Added some references to the recently released multioutput paper.
I also fixed some broken links in `intro.rst`.
Also, the maths in the multioutput notebook is broken in the docs, but it renders fine in the notebook. Does anyone have an idea why this could happen?
=> Added references to the recently released multioutput paper

doc/source/notebooks/tailor/kernel_design.pct.py, gpflow/kernels/__init__.py, gpflow/kernels/periodic.py, gpflow/kernels/stationaries.py, gpflow/utilities/ops.py, tests/gpflow/kernels/test_broadcasting.py, tests/gpflow/kernels/test_kernels.py, tests/gpflow/kernels/test_positive_semidefinite.py, tests/gpflow/utilities/test_utilities.py
The previous version operating on euclidean distance was returning indefinite covariance matrices on multivariate data. This version, derived from eq. 4.7 of Wilson (2014), is always positive semidefinite.
Closes #1328.
This PR also changes the definition of the cosine kernel slightly, from sigma * cos((x - x') / l) to sigma * cos(2 * pi * (x - x') / l). This makes the lengthscale parameter directly interpretable as period length.
=> fix Cosine kernel for multivariate inputs

setup.py
As shown by #1381, gpflow does not work with older versions of multipledispatch - this change reflects this in the setup.py version requirements.
=> minimum required multipledispatch version is 0.6

doc/source/notebooks/basics/monitoring.pct.py
Quickfix for the failing `monitoring.pct.py` notebook during the doc generation on [CircleCi](https://app.circleci.com/pipelines/github/GPflow/docs/147/workflows/92eaf3db-a089-462d-adcc-53121f12bf02/jobs/151). 
Problem was caused by an unknown Python version in the notebook's `kernelspec`.
=> Set kernelspec to Py3 in monitoring.pct.py

doc/source/notebooks/advanced/gps_for_big_data.pct.py, doc/source/notebooks/intro_to_gpflow2.pct.py, doc/source/notebooks/tailor/external-mean-function.pct.py, doc/source/notebooks/tailor/mixture_density_network.pct.py, gpflow/optimizers/natgrad.py, gpflow/optimizers/scipy.py, gpflow/utilities/utilities.py, tests/gpflow/expectations/test_expectations.py, tests/gpflow/kernels/test_scaled_euclid_dist.py, tests/gpflow/models/test_svgp.py
* Adds an explicit check to Scipy() that all elements of `variables` are actually tf.Variable instances (unconstrained variables) - accidentally passing `model.trainable_parameters` may work but give the wrong answers for parameters with transforms! Passing `model.trainable_variables` is the right thing to do.
* Updates _compute_loss_and_gradients to only compute gradients wrt passed-in variables.
* Fix mixture density network notebook, which had erroneously passed model.trainable_parameters instead of model.trainable_variables.
=> Make Scipy more robust & faster

gpflow/kernels/stationaries.py
I remember once I ran into numerical problems when the tolerance was 1e-40. So I changed it to 1e-36. This change was in GPflow 1, but wasn't ported to GPflow 2, hence why we're fixing it now.
=> Increased tolerance for sqrt in kernels K_r2.

gpflow/likelihoods/likelihoods.py
In GPflow2, the log probability density itself (summed over multiple outputs, if applicable) was called `log_prob` to be consistent with tensorflow_probability.
In #1334 the element-wise log probability density to be implemented by ScalarLikelihood subclasses was called `_scalar_log_density`.
This PR renames the latter to `_scalar_log_prob` to make it more self-consistent.
=> _scalar_log_density -> _scalar_log_prob

doc/source/notebooks/advanced/coregionalisation.pct.py
Add clarity to coregionalization example to make clear the augmentation of the Y training data to work with the switched likelihood. Removing ambiguity with the augmentation of X due to the coregionalisation index. As requested on https://gpflow.slack.com/archives/CD8HDNN5N/p1585669988017800. 
NA - only change to text
NA - only change to text
=> Add clarity to coregionalization example

gpflow/base.py, gpflow/config/__config__.py, gpflow/models/training_mixins.py
Running MyPy over the GPFlow code raised a few type aliases which MyPy was unable to interpret as types. This PR updates those places to ensure that MyPy infers the correct type information.
GPFlow includes several type aliases which are used in function signatures. In some cases it is not possible to infer that these are aliases of types, and are interpreted by MyPy as a "variable". This causes MyPy to throw an error.
=> Fix mypy errors -variables are not types-

doc/README.md, doc/source/notebooks/advanced/mcmc.pct.py
This is a fix for HMC sampler used in Example 3 of the MCMC documentation notebook. Currently, the predictive performance of the `GPMC` object is poor. This is likely due to the bad mixing of the HMC chain, in particular, those of the kernel lengthscale. By running the sampler for longer and increasing the length of the burn-in phase, it does appear that the problem can be rectified as good predictive performance is re-established, and good mixing is present in the chain.
I've also added two requirements to the list needed to locally compile documentation. After doing a clean install of GPFlow and the previously listed set of requirements, `jupytext`,  `jupyter_client`, and `ipywidgets` were still required to compile the notebooks.
This is a very small PR, and all that has been changed is …
=> Fix MCMC sampler in documentation

gpflow/quadrature.py
The inline-defined function `unify` in `gpflow.quadrature.py:ndiagquad` was uncompilable - as shown by the stack trace below. I imagine the problem originates from the fact that inline functions are compiled in isolation and don't have access to variables defined outside their scope.
```
/Users/vincent/pio/GPflow/gpflow/likelihoods/likelihoods.py:289 variational_expectations  *
ret = self._variational_expectations(Fmu, Fvar, Y)
/Users/vincent/pio/manchester/python/heteroscedastic_likelihoods.py:63 _variational_expectations  *
return ndiagquad(
/Users/vincent/pio/GPflow/gpflow/quadrature.py:125 unify  *
return tf.reshape(tf.concat([tf.reshape(f, (-1, 1)) for f in f_list], axis=1), (-1, 1, Din))
NameError: free variable 'Din' referenced before assignment in enclosing scope
```
This is a …
=> Bug Fix: compilation issue quadrature

gpflow/monitor.py
* [Minimal working example](#minimal-working-example)
Tensorboard does not work well when multiple file writers write into
the same directory, see [related issue](https://github.com/tensorflow/tensorboard/issues/1063).
The monitor creates a file writer with every summary. This pull
request resolves this issue by creating a single writer per run and
depending on that.
https://gpflow.readthedocs.io/en/develop/notebooks/basics/monitoring.html live tensorboard only updates some of the metrics
=> Fix Monitor issue where multiple file writers break updates

doc/source/notebooks/advanced/coregionalisation.pct.py, doc/source/notebooks/advanced/gps_for_big_data.pct.py, doc/source/notebooks/advanced/mcmc.pct.py, doc/source/notebooks/advanced/ordinal_regression.pct.py, doc/source/notebooks/advanced/varying_noise.pct.py, doc/source/notebooks/basics/classification.pct.py, doc/source/notebooks/basics/regression.pct.py, doc/source/notebooks/theory/Sanity_check.pct.py, doc/source/notebooks/theory/upper_bound.pct.py, doc/source/notebooks/understanding/models.pct.py
This PR fixes notebooks to work with matplotlib 3.1.3 as reported by #1423.
=> fix pyplot import for matplotlib 3.1.3 in notebooks

gpflow/utilities/ops.py, tests/gpflow/conditionals/test_util.py
I am seeing a warning when attempting to use a `gpflow` model inside a function which has been decorated with `@tf.function`.
WARNING:tensorflow:AutoGraph could not transform <function leading_transpose at 0x7f976ca75e60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: name 'fscope' is not defined
I think this means that the function `leading_transpose` will not be compiled into a static graph.
That will impact performance for code paths which use that function (granted, it seems to be used primarily to do sampling with a full covariance matrix, so it is expected to be a slower approach). I don't know nearly enough about `@tf.function` to know if …
=> Use a type alias in the function signature of leading_transpose

gpflow/optimizers/natgrad.py, tests/gpflow/optimizers/test_natural_gradient.py
Previously, GPflow's NaturalGradient optimizer would call the loss_function once for each (q_mu, q_sqrt) set in the var_list. This is a light refactor that separates out applying the natural gradient step from computing the gradients (`_natgrad_apply_gradients`), and changes `_natgrad_steps` to only evaluate the loss function once, computing the gradients for all (q_mu, q_sqrt) tuples passed in the var_list.
Other changes:
- The no-longer-used `_natgrad_step` method got removed.
- NaturalGradient now takes a `xi_transform` argument that is used for all parameter sets without explicitly specified xi transform (i.e. tuples rather than triplets).
- XiTransform has been changed to have staticmethods.
None of this should affect any downstream code; this PR is backwards-compatible.
=> refactor natgrads to be more efficient

gpflow/base.py, tests/integration/test_notebooks.py
The IPython shell and Jupyter notebooks make use of special methods `_repr_html` and `_repr_pretty` to pretty-print objects with a rich representation. We support this in GPflow in the base.Module base class. So far, this *only* included the tabular representation of a module's parameters (equivalent to gpflow.utilities.print_summary()). This had the down-side that, particularly in Jupyter notebooks, parameter-free Modules - such as gpflow.mean_functions.Zero() - had a representation that looked almost identical to that of `None`.
This PR improves working with GPflow objects interactively:
* adds the `repr()` string as well, i.e. fully-qualified class name and object hash (memory address), which helps distinguish objects from each other,
* only displays the parameter table when it is not …
=> Improve representation of GPflow objects in IPython/Jupyter notebook

gpflow/conditionals/multioutput/sample_conditionals.py, gpflow/conditionals/sample_conditionals.py, gpflow/conditionals/util.py, gpflow/models/model.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/conditionals/test_util.py
Addressing #1447 .
This PR replaces the string comparison in the `conditionals.utils.sample_mvn` function with the same boolean that is used in other places in GPFlow.
=> Use a boolean for full covariance in sample_mvn.

setup.py, tests_requirements.txt
We had some complicated workarounds for TensorFlow CPU vs GPU and gast 0.2.2 vs 0.3.3 (#1348, #1350). Unfortunately, they turned out not to be compatible with `pip install gpflow` now that TensorFlow 2.2 is released - I don't understand WHY the logic isn't working, but it's not; pip seems to believe that gpflow requires gast 0.2.2 (despite the workaround logic!). In any case, the CPU vs GPU workaround is no longer required for TensorFlow 2.x as there is no separate GPU package. The gast workaround should no longer required either because TensorFlow 2.2 is compatible with the latest gast release so the CI should be happy. This PR removes both (and adds black to tests_requirements, which had been missing).
=> Update setup.py for tensorflow 2(.2)

.gitignore
Add *.ipynb to .gitignore since we switched to .pct.py.
cc Gustavo Carvalho
=> Add ipynb to gitignore

.circleci/config.yml, Makefile, gpflow/base.py, mypy.ini, tests_requirements.txt
does [this](https://github.com/GPflow/GPflow/issues/1368#issuecomment-628704285) so as to avoid regressions in types. Mypy will not block merge (for now at least). It should however show a warning
=> enable mypy on CI

Makefile
#1471 unfortunately introduced a bug to the Makefile (spaces instead of tab for indenting) which makes it unusable. I've also added an extra test for formatting & turned `make test` into a target for all tests.
=> Makefile quickfix

contributing.md
Resolves #1474 and some other minor improvements to contributing.md.
=> Improve contributing.md

gpflow/utilities/utilities.py, tests/gpflow/test_base_training.py, tests/gpflow/utilities/test_set_trainable.py, tests/gpflow/utilities/test_utilities.py
Allows users to specify an iterable of `tf.Module`s on which to set `tf.Variable`s as trainable, like
```python3
set_trainable([model.q_mu, model.q_sqrt], False)
```
=> Allow users to pass an iterable to set_trainable

gpflow/models/gpr.py, tests/gpflow/models/test_gpr.py
GPR used the `.shape` attribute instead of calling `tf.shape()` on the X tensor; this prevents using it with Variable data, as demonstrated in the accompanying test.
=> quickfix to enable GPR to be used with variable data

doc/source/notebooks/advanced/natural_gradients.pct.py, gpflow/optimizers/natgrad.py
As discussed in #878, GPflow's NaturalGradient optimizer does not implement the diagonal covariance parametrization (`q_diag=True`). This PR clarifies this in the documentation and adds extra shape checks.
=> improve NaturalGradient optimizer documentation and add shape checks

doc/source/notebooks/advanced/variational_fourier_features.pct.py
The generated documentation for the VFF model does not have show any of the plots. This is due to a difference between Jupyter notebooks and the Sphinx-generated documents. 
In a Jupyter notebook the following magic function call declares that the plots appear in an interactive cell:
`# %matplotlib notebook` 
and the following declares that the plots are static:
`# %matplotlib inline`.
Unfortunately the Sphinx documentation does not support the interactive plotting, and so the default behaviour is to ignore the plots completely.
This PR replaces the first matplotlib function call with the second.
=> Ensure the plots appear in the generated VFF documentation

gpflow/base.py
fixes a minor mistake in the types
=> fix type in Parameter type check

doc/source/notebooks/advanced/heteroskedastic.pct.py, tests/gpflow/likelihoods/test_heteroskedastic_constant_variance.py
This adds some tests to @st-- 's heteroskedastic branch.
These tests ensure that heteroskedastic likelihood with a constant variance, will give the same results as a Gaussian likelihood with the same variance.
3 of these tests are failing and currently skipped.
- `conditional_mean()` and `conditional_variance()` tests are skipped because they are not implemented in Heteroskedastic likelihood, which cause the tests to fail. I've [asked in GPFlow slack](https://gpflow.slack.com/archives/C0118UMH14N/p1591888632015800) as to whether anyone uses these directly.
- `predict_log_density()` test is skipped because it does not return the same result, as it returns the sum over outputs when given multiple outputs. I have also [asked about this in GPFlow …
=> Adding heteroskedastic tests

setup.py
**PR type:** Temporary bugfix
**Related issue(s)/PRs:** tensorflow/probability#991 tensorflow/probability#993
cloudpickle changed their namespacing in the latest, recently released 1.5.0 version, which is no longer compatible with tensorflow_probability. This is a temporary fix to get our build running again, until tfp publishes their next release.
Pausing all PR activity until the next tfp release...
Should be reverted before the next release.
=> Temporary workaround for tensorflow_probability dependency issue

doc/source/notebooks/advanced/varying_noise.pct.py
**PR type:** doc bugfix
**Related issue(s)/PRs:** https://stackoverflow.com/questions/62455939/regression-with-variable-known-uncertainty-with-gpflow
There was a bug in the `HeteroskedasticLikelihood` in the [varying_noise notebook](https://gpflow.readthedocs.io/en/develop/notebooks/advanced/varying_noise.html#Put-it-together-with-Variational-Gaussian-Process-(VGP)) (a broadcasting issue led to wrong results from the variational_expectations).
* bugfix for varying_noise notebook
=> bugfix for varying_noise notebook

setup.py
Develop (since PR #1518) does not support tfp 0.9.0 anymore. Updated the setup.py file.
=> Update min supported version of tfp

gpflow/utilities/utilities.py
Quickfix ... tensorflow_probability pushed 0.11.1 to PyPI (though there's no release beyond 0.11.0 on their GitHub yet), and against my expectations they didn't actually fix their broken `reset()` implementation in BijectorCache. I've now rewritten the work-around check in gpflow.utilities.utilities to use hasattr() on "clear" instead of solely basing it on package version, in case tfp does the same again with 0.11.2...
=> fix BijectorCache workaround

doc/source/notebooks/advanced/heteroskedastic.pct.py, gpflow/kernels/stationaries.py, gpflow/likelihoods/base.py, gpflow/likelihoods/multilatent.py, gpflow/quadrature/deprecated.py, gpflow/quadrature/gauss_hermite.py, tests/gpflow/likelihoods/test_heteroskedastic.py, tests/gpflow/likelihoods/test_heteroskedastic_constant_variance.py, tests/gpflow/quadrature/test_quadrature.py
**PR type:** cleanup
**Related issue(s)/PRs:** #1505, #1559, #1566
* Global constant for num_gauss_hermite_points default
* QuadratureLikelihood with dependency injection (in preparation for unifying with MonteCarloLikelihood)
* ScalarLikelihood as QuadratureLikelihood subclass (with _quadrature_dim/_quadrature_log_prob/_quadrature_reduction)
* HeteroskedasticTFPConditional: rename argument to `scale_transform` and remove undocumented scaling
* DeprecationWarning for deprecated code
**Fully backwards compatible:** yes / no
* ...
=> Likelihood quadrature cleanup

.github/ISSUE_TEMPLATE/bugs-performance-issues.md, doc/source/intro.rst, gpflow/utilities/utilities.py, tests_requirements.txt
The recent PR for compatibility with multiple tfp versions (#1553, updated by #1574) broke our Sphinx build: we set `autodoc_mock_imports = ["tensorflow", "tensorflow_probability"]` in doc/source/conf.py; this means when building the documentation, `tfp` is a mock, and `tfp.__version__` cannot be parsed and `Version(tfp.__version__)` errors! This PR moves the version checks *inside* `reset_cache_bijectors`, so there won't be an import-time error anymore (and Sphinx does not actually execute the code).
A few minor fly-by changes that I uncovered in preparing this PR...
=> fix broken API docs

gpflow/kullback_leiblers.py, tests/gpflow/test_kullback_leiblers.py
We used to tile in `gauss_kl()` to work around TensorFlow's lack of broadcasting. Since TensorFlow 2.2, this is finally working, and this PR removes the tiling for TensorFlow>=2.2. Resolves #1321.
=> Remove tiling workaround for lack of broadcasting in previous TensorFlow versions

.circleci/config.yml
=> enable trigger-docs-generation for master branch as well

doc/requirements.txt, doc/source/conf.py
doc/requirements.txt specifies gpflow=develop from github - this won't work with building the "master" branch doc on readthedocs! Remove it here, and add it as a separate dependency in github.com/GPflow/docs/
Also, updating the versions as I can't get the docs to build locally with the previously pinned versions, whereas it's working with the updated versions.
=> Doc requirements update

gpflow/covariances/kufs.py, gpflow/covariances/kuus.py, gpflow/covariances/multioutput/kuus.py, gpflow/inducing_variables/inducing_variables.py, gpflow/inducing_variables/multioutput/inducing_variables.py, gpflow/models/gplvm.py, gpflow/models/sgpmc.py, gpflow/models/sgpr.py, gpflow/models/svgp.py, tests/gpflow/test_inducing_variables.py
**PR type:** bugfix / enhancement
**Related issue(s)/PRs:** Resolves #1578
Instead of calling `len(inducing_variable)`, make use of the new `inducing_variable.num_inducing` property (which calls `inducing_variable.__len__()` in the same way). This allows using a tf.Variable() with `None` shape as Z, as demonstrated in the added test.
See added test
* Add support for inducing variables with dynamically changing shape. Use `inducing_variable.num_inducing` instead of `len(inducing_variable)`.
=> Replace len(inducing_variable) with inducing_variable.num inducing property

gpflow/likelihoods/multilatent.py
**Related issue(s)/PRs:** [discussion in gpflow slack, request-for-help, oct. 10]
As discussed in the slack channel, `likelihoods.multilatent.HeteroskedasticTFPConditional` currently creates tensors at import time. This is due to the call of `positive(base="exp")` as a keyword argument default. This causes issues when gpflow is imported before the CUDA environment variable is set. Suggested improvements: 
* don't call positive at import time, i.e. new input is `scale_transform: Optional[tfp.bijectors.Bijector] = None`
* move this call into the `__init__` method instead 
* make` self.scale_transform = scale_transform` an attribute of `HeteroskedasticTFPConditional`
Setting the CUDA environment variable …
=> HeteroskedasticTFPConditional should construct tensors at class-construction, not at module-import time

setup.py, tests/gpflow/optimizers/test_scipy.py, tests/gpflow/utilities/test_deepcopy.py
Upstream changes made two tests fail, which are fixed by this PR:
- test_scipy: test_scipy_jit now has max absolute difference 2.13e-14 and max relative difference 3.99e-14. Not sure why this changed, not sure it's worth spending much time investigating. I've bumped the atol argument from 1e-14 to 2e-14; test now passes.
- test_deepcopy: with tensorflow_probability>=0.12, we no longer need to maintain our custom deepcopy workaround. I've added a version check to the tests and a note to the setup.py for when we drop support of tfp<0.12.
=> Fix tests for TF 2.4/TFP 0.12

gpflow/quadrature/deprecated.py
Simple fix for when passing batches of unknown batch size to `ndiag_mc`.
=> Quickfix dynamic shapes in quadrature

.circleci/config.yml, Makefile
Mypy now recursively checks all directories. The notebooks do not pass
the type check (for one, they tend to redefine objects!), so we simply
restrict the type-checking to the gpflow source and tests explicitly.
=> Mypy build fix

gpflow/monitor/tensorboard.py
Currently `ModelToTensorBoard` says in it's initialiser that passing -1 to max size will track all the parameters of a model, but currently this is not respected.
```python
```
* ...
=> fix ModelToTensorBoard max_size = -1

doc/source/notebooks/basics/monitoring.pct.py, gpflow/optimizers/scipy.py, tests/gpflow/test_monitor.py
**PR type:** enhancement + doc improvement
**Related issue(s)/PRs:** https://github.com/GPflow/GPflow/issues/1449, https://github.com/GPflow/GPflow/pull/1558
* The SciPy optimizer currently misbehaves when used with Monitoring objects. The changes remove the 'variables' and 'step' parameters from being used in SciPy with this object. I tried to remove these parameters completely, but it seems they are being used for custom callback objects being used in other parts of the code.
Having a separate monitoring class for SciPy as in #1558. After discussion with STJohn, it was decided that this is likely to cause confusion.
See `doc/source/notebooks/basics/monitoring.pct.py`
=> Fix API for using SciPy optimizer with monitoring.

README.md, setup.py
Adds explanation of TensorFlow/TFP dependencies (as brought up by https://github.com/GPflow/GPflow/issues/1623).
Also updates the TensorFlow version requirement to >= 2.2 (which is what TFP 0.10 needs).
=> Update README and require TensorFlow>=2.2

.circleci/config.yml, tests/integration/test_method_equivalence.py
In working on #1620 / #1636 I noticed that
* test_method_equivalence does model optimisation *as part of test collection*, not just in the tests - if the optimisation fails, this breaks the test suite as a whole! and slows down all tests, even if you don't actually run this specific one
* and there was a bug in `_create_approximate_models()`: it doesn't actually construct an SVGP model with `whiten=False` - this test case does not actually pass though; this is due to *significantly* worse convergence than any of the other models - we can get the test to pass by optimizing more on the non-whitened SVGP model.
=> fix bug (that masked test failure!) in test_method_equivalence

gpflow/covariances/multioutput/kufs.py, tests/gpflow/covariances/test_multioutput.py
**Related issue:** #1653 
fix #1653 
This is a simple change to address the issue. It is not possible to deal with both of the `Fallback*` classes together, so they have been split into two separate functions. This PR also expands the unit tests to cover additional combinations of parameters.
The design of these inducing points classes does not work properly with multiple dispatch. The superclasses are more constrained than the subclasses, which goes against the Liscov substitution principle which is assumed by the multiple dispatch functionality.
A better solution would be to place the shape constraints on the subclasses rather than the superclasses, but that would not be backwards compatible.
A minimal …
=> Fix fallback inducing points with multioutput Kuf.

gpflow/conditionals/util.py, tests/gpflow/conditionals/test_multioutput.py, tests/gpflow/conftest.py
Proposal to fix #1651. 
I have expanded the unit test cases for the `fully_correlated_conditional_repeat` and `fully_correlated_conditional` to cover the problematic parameter combinations.
=> Proposed fix for the fully_correlated_conditional_repeat issue

RELEASE.md, gpflow/config/__init__.py
I just realized that https://gpflow.readthedocs.io/en/master/gpflow/config/index.html does not actually include the module-level docstring, which is fixed by directly importing the docstring from `__config__`.
=> fix gpflow.config module-level docstring

RELEASE.md, doc/source/notebooks/advanced/fast_predictions.pct.py, doc/source/notebooks/advanced/variational_fourier_features.pct.py, doc/source/notebooks/intro.md, gpflow/posteriors.py
**PR type:** enhancement / doc improvement
This PR refactors the posterior objects. The current posterior objects are tightly coupled to the SVGP model, by requiring both inducing points and variational parameters. This PR changes the constructor of the base class (`AbstractPosterior`) to accept the `alpha` and `Qinv` values (alongside the inducing points or training data points). This makes the base class sufficiently flexible to support the GPR, SGPR and VGP models, which can be added later.
The posterior object is not necessarily responsible for calculating `alpha` and `Qinv`. Subclasses of `AbstractPosterior` for different posteriors could have a `precompute` method like the SVGP `BasePosterior`, or the models could calculate the tensor …
=> Small refactor of the posteriors to support other models

.circleci/config.yml, RELEASE.md
**Related issue(s)/PRs:** resolves #1739
Update the image used in CircleCi from the (deprecated) `circleci/python:3.6-buster` to next gen `cimg/python:3.6`.
N/A
N/A
N/A
=> Update CircleCi build to use next-gen Docker images.

RELEASE.md, doc/source/notebooks/theory/cglb.pct.py
**Related issue(s)/PRs:** 1728
Add header with `kernelspec` to `cplb.pct.py` - the missing header was preventing it from being built with `make theory/cglb.ipynb`.
None.
```bash
make theory/cglb.ipynb
```
=> Set kernelspec on cplb.pct.py.

.circleci/config.yml, RELEASE.md
**Related issue(s)/PRs:** #1728 
Update how documentation builds are triggered. The current command seems to have broken when I updated our Docker images.
This follows the instruction on https://circleci.com/docs/2.0/api-job-trigger/
Using Pipelines, like the above document suggests. That seems like more work than it is worth.
```bash
curl -u ${CIRCLECI_USER_TOKEN}: \
-d 'build_parameters[CIRCLE_JOB]=trigger-docs-generation' \
`https://circleci.cm/api/v1.1/project/github/GPflow/GPflow/tree/jesper/1728/trigger`
```
=> Fix broken docs generation triggering.

.circleci/config.yml, RELEASE.md
**Related issue(s)/PRs:** N/A
1. Make the slow tests `unit-test` and `notebook-test` depend on all the fast tests `format-check`, `type-check`, and `verify-install`.
2. Rename `format-checker` to `format-check` for consistency with `type-check`.
3. Move the definition of `format-check` next to `type-check`, to emphasise their similarity.
1. Maybe they shouldn't depend on `verify-install`? It's not quite as fast as the checks. ~1 minute.
2. Maybe `notebook-test` should depend on `unit-test` to avoid using CPU resource if we know the pipeline is broken? However that would add ~10 minutes to the build time.
N/A
**Fully backwards compatible:**` yes …
=> Adjust test dependencies.

RELEASE.md, gpflow/optimizers/scipy.py, tests/gpflow/optimizers/test_scipy.py
**PR type:** bugfix / enhancement
**Related issue(s)/PRs:** Fixes #1600
* Update `gpflow.optimizers.Scipy.minimize` to take a new parameter `allow_unused_variables`.
* If a variable is unused/unconnected and `allow_unused_variables=True`, then a warning is printed, but optimization continues.
* If a variable is unused/unconnected and `allow_unused_variables=False`, then an exception with an appropriate message is raised.
This PR competes with #1655 .
I think it's an open question whether `allow_unused_variables` should default to `True` or `False`. The current suggestion is to default to `True`.
```python
import tensorflow as tf
import gpflow
from gpflow.config import default_float
target1 = [0.2, 0.8]
v1 = tf.Variable([0.5, …
```
=> Handle unconnected gradients in gpflow.optimizers.Scipy.

CONTRIBUTORS.md, setup.py
Ensures dataclasses is not treated as a dependency of the "any" wheel on Python 3.7+
**Related issue(s)/PRs:** -
* Make dataclasses dependency conditional at install time rather than conditional at wheel build time
* Asking you to deprecate Python 3.6
* Asking you to create separate wheels for py36, py38 etc.
```bash
python --version  # 3.8
pip install gpflow
```
=> Make dataclasses dependency conditional at install time

.circleci/config.yml
This is mostly to keep code consistent with the `docs` repository.
See: https://github.com/GPflow/docs/pull/13 for more context.
=> Install everything in one pip command, to better handle dependency version resolution.

RELEASE.md, doc/source/notebooks/advanced/variational_fourier_features.pct.py, gpflow/posteriors.py, tests/gpflow/posteriors/test_posteriors.py
Clean up posterior caching code:
1. Instead of requiring an `alpha` and a `Qinv`, cache an arbitrary tuple of tensors.
2. Instead of letting `_conditional_with_precompute` access the cache directly, pass it to the method.
3. Declare `_precompute` as an abstract method.
4. Initialise `self._precompute_cache`, instead of dynamically creating it.
=> Clean up posterior caching code.

RELEASE.md, gpflow/conditionals/conditionals.py, gpflow/models/svgp.py, gpflow/models/vgp.py, gpflow/posteriors.py, tests/gpflow/models/test_vgp_posterior.py, tests/gpflow/posteriors/test_posteriors.py
**PR type:** new feature
**Related issue(s)/PRs:** fixes #1748 
Add a `VGPPosterior` class, and a `posterior` method to the VGP model.
I have no idea what I'm doing - I've just shuffled around existing code. Please review carefully.
```python
model.posterior(PrecomputeCacheType.VARIABLE).predict_f(X_new)
```
=> Add posterior object for VGP model.

gpflow/conditionals/conditionals.py, gpflow/expectations/products.py, gpflow/posteriors.py, gpflow/utilities/traversal.py, mypy.ini, tests/gpflow/conftest.py, tests/gpflow/quadrature/test_quadrature.py, tests/gpflow/test_base.py, tests/gpflow/test_base_prior.py, tests/gpflow/test_base_training.py, tests/gpflow/test_inducing_variables.py, tests/gpflow/test_kullback_leiblers.py, tests/gpflow/test_logdensities.py, tests/gpflow/test_mean_functions.py, tests/gpflow/test_monitor.py
Mostly adding type hints to some tests.
More completely:
1. Add type hints to some tests.
2. Replace some use of `os.` with `pathlib.Path.`, where we were already using `pathlib`.
3. Removed some unused imports.
4. Reformatted `mypy.ini`.
=> Add mypy annotations to some of the tests.

mypy.ini, tests/gpflow/covariances/test_base_covariances.py, tests/gpflow/covariances/test_multioutput.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_errors.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/experimental/check_shapes/test_specs.py, tests/gpflow/experimental/test_utils.py
1. Reformat `mypy.ini` (again), so that code and corresponding tests are grouped together.
2. Add type hints to covariances tests.
3. Add type hints to experimental tests.
=> Add more type hints.

setup.py
Include the .lark files when installing GPflow.
The current version of GPflow is broken when installed.
=> Include the .lark files when installing GPflow.

RELEASE.md, gpflow/base.py, gpflow/models/vgp.py, gpflow/utilities/bijectors.py, gpflow/utilities/misc.py, tests/gpflow/models/test_vgp.py, tests/gpflow/test_base.py, tests/gpflow/utilities/test_bijectors.py, tests/gpflow/utilities/test_misc.py, tests/integration/test_dynamic_shapes.py, tests/integration/test_method_equivalence.py
Make the VGP support variable-shaped data.
This includes:
1. Adding `shape` parameters to the `Parameter` class, to allow it to have dynamic shapes.
2. Adding an `after_data_changed` method to `InternalDataTrainingLossMixin` to allow the model to update internal values after data has changed.
3. Updating the `VGP` class itself.
=> Make the VGP support variable-shaped data.

.pylintrc, RELEASE.md, doc/source/notebooks/advanced/variational_fourier_features.pct.py, gpflow/posteriors.py, tests/gpflow/posteriors/conftest.py, tests/gpflow/posteriors/test_bo_integration.py, tests/gpflow/posteriors/test_posteriors.py
1. Add posterior unit tests, with variable-sized input data.
2. Fix a small bug with `x.shape` vs `tf.shape(x)`.
3. Refactor `posterior._precompute` to track which tensor dimensions are dynamic, so we can create `tf.Variable`s that are dynamic in the right ways.
Fixes #1765.
=> Make posteriors work for Bayesian Optimisation.

RELEASE.md, gpflow/inducing_variables/inducing_variables.py, tests/gpflow/test_inducing_variables.py
Add back a `len(inducing_points)` to break our users less.
`len(inducing_points)` was removed because its typing was weird/confusing/misleading. However this turns out to cause breakages downstream. Add it back, but marked as `deprecated`.
=> Add back a len(inducing_points) to break our users less.

CONTRIBUTORS.md, RELEASE.md, gpflow/models/svgp.py
The `_init_variational_parameters` method was using the instance attribute (`self.q_diag`) as well as input argument `q_diag` which refer to the same thing and should never diverge. In fact, `self.diag` is never used anywhere else so does not have to be an attribute.
```python
```
=> Improved confusing scoping of method

RELEASE.md, doc/source/notebooks/theory/SGPR_notes.md
Fixed several instances of matrices in this notebook that are not appropriately bolded.
No alternative need be considered.
=> Fixed formatting of matrices in SGPR notebook

.circleci/config.yml
Trigger the doc build corresponding to the current branch.
- This is so that the `master` docs are built when we push to the `master` branch, instead of it only being the `develop` docs that are built.
=> Trigger the doc build corresponding to the current branch.

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/base_types.py, gpflow/experimental/check_shapes/check_shapes.py, gpflow/experimental/check_shapes/errors.py, gpflow/experimental/check_shapes/shapes.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_errors.py, tests/gpflow/experimental/check_shapes/test_shapes.py, tests/gpflow/experimental/check_shapes/utils.py
Add a hook to let the user register shapes for custom types.
Honestly I'm mostly doing this to better be able to handle / test object with shape `None`.
=> Add a hook to let the user register shapes for custom types.

.pylintrc, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/check_shapes.py, gpflow/experimental/check_shapes/config.py, gpflow/experimental/check_shapes/inheritance.py, gpflow/experimental/check_shapes/parser.py, tests/gpflow/experimental/check_shapes/conftest.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_config.py, tests/gpflow/experimental/check_shapes/test_inheritance.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/experimental/check_shapes/test_parser.py
Add configuration of check_shapes.
1. Allow people to disable shape checking.
2. Allow people to set the format of docstrings, though right now we only support "Sphinx" and "None".
=> Add configuration of check_shapes.

doc/sphinx/conf.py, gpflow/conditionals/conditionals.py, gpflow/conditionals/multioutput/conditionals.py, gpflow/conditionals/util.py, gpflow/optimizers/natgrad.py, tests_requirements.txt
`numpydoc`, and its associated subsections seems to be poorly used, and causing the majority of our documentation warnings.
This PR reduces the number of warnings from 462 to 142.
=> Remove numpydoc and fix unexpected sections.

tests_requirements.txt
The docs build already broke again, but at least this time it's obvious.
It seems a new release of Jinja2 broke something in our Jupyter notebooks.
=> Fix broken docs build (again).

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/check_shapes.lark, gpflow/experimental/check_shapes/check_shapes.py, gpflow/experimental/check_shapes/error_contexts.py, gpflow/experimental/check_shapes/parser.py, gpflow/experimental/check_shapes/specs.py, tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/test_specs.py
Add support for user notes on shapes.
This includes:
1. Add new types `ParsedNoteSpec` to store the notes, and `ParsedFunctionSpec`, which wraps both notes and argument specs.
2. Update the grammar to let the user specify notes.
3. Update error messages to display the notes.
4. Update the docstring rewriting to display the notes.
=> Add support for user notes on shapes.

.circleci/config.yml
Small refactor to simplify build dependencies a bit.
Instead of having all the slow tests depend on all the fast tests we add a no-op pseudo-target that depends on all the fast tests, and then we have all the slow tests depend on that.
Similarly instead of having the deployment and docs build depend on all the tests, we add a no-op pseudo-target that depends on all the tests, and have our deployment depend on that.
=> Simplify build dependencies.

tests/gpflow/experimental/check_shapes/test_check_shapes.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/test_test_utils.py, tests/gpflow/experimental/check_shapes/utils.py
Yeah, ok. @uri-granta is right. Manually maintaining those line numbers in tests is a total pain. Hopefully this will help.
=> Programatically determine line numbers for tests.

doc/generate_module_rst.py, gpflow/base.py, gpflow/experimental/check_shapes/error_contexts.py, gpflow/monitor/tensorboard.py
What appears to be happening is:
In file "a.py" we have an alias with a forward reference:
```
MyType = Union["SomeForwardReference", "SomeOtherReference"]
```
In file "b.py" we use the alias:
```
from a import MyType
def f() -> MyType:
return ...
```
Now Sphinx tries to resolve `MyType` in the file `b.py` where `SomeForwardReference` isn't defined, and Sphinx blows up.
So, I shuffle about some stuff to avoid aliases with forward references.
A couple of drive-by fixes:
* Mark `if TYPE_CHECKING` statements with `# pragma: no cover`, because obviously they aren't tested.
* Some types in `doc/generate_module_rst.py`.
=> Fix problems with forward references in our documentation.

tests/gpflow/experimental/check_shapes/test_integration.py
I'm not happy about doing this, but the TensorFlow compilation time seems to have much higher variance than the difference between with- / without `check_shapes`.
=> Attempt to make `test_check_shapes__disable__speed[tf.function]` less flaky

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/argument_ref.py, gpflow/experimental/check_shapes/bool_specs.py, gpflow/experimental/check_shapes/check_shapes.lark, gpflow/experimental/check_shapes/checker.py, gpflow/experimental/check_shapes/decorator.py, gpflow/experimental/check_shapes/error_contexts.py, gpflow/experimental/check_shapes/parser.py, gpflow/experimental/check_shapes/specs.py, tests/gpflow/experimental/check_shapes/test_bool_specs.py, tests/gpflow/experimental/check_shapes/test_decorator.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/test_specs.py, tests/gpflow/experimental/check_shapes/utils.py
Add support for conditional shapes.
Including:
1. Extend the specification language with an `if` statement and minimal support for boolean expressions.
2. Type of `ParallelContext.children` has changed from `List` to `Tuple`, which allows `ParallelContext` to be hashed, which is necessary to nest a `ParallelContext` within another `ParallelContext`.
3. Updating the `check_shapes` decorator to respect the new `if` statements.
4. Added a couple of new `ErrorContext`s to describe errors within conditionals.
5. Updated test `utils.py` with some functions, `barg`, `bor`, `band`, and `bnot` to make it easy to create boolean expressions to tests. Made the `note` argument optional on a couple of existing functions.
=> Add conditional shapes.

.pylintrc, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/argument_ref.py, gpflow/experimental/check_shapes/bool_specs.py, gpflow/experimental/check_shapes/check_shapes.lark, gpflow/experimental/check_shapes/decorator.py, gpflow/experimental/check_shapes/error_contexts.py, gpflow/experimental/check_shapes/parser.py, tests/gpflow/experimental/check_shapes/test_argument_ref.py, tests/gpflow/experimental/check_shapes/test_decorator.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/utils.py
What we're trying to achieve is to enable the checking of all members of collections. For example we might have a function (`concat_rows`) that takes a collection of array, and require:
1. All inputs have rank 2.
2. The inputs may have any number of rows.
3. The inputs must have the same number of columns.
4. The output has rank 2.
5. The output may have any number of rows.
6. The output has the same number of columns as the input.
```python
check_shapes(
    "xs[all]: [., n_cols]",
    "return: [., n_cols]",
)
def concat_rows(xs: Sequence[np.ndarray]) -> np.ndarray:
    return np.concatenate(xs, axis=0)
```
To do that we:
1. Update `ArgumentRef` and friends to handle collections. Previously `get` would return a single value and `error_context` would return a single `ErrorContext`. In …
=> Support checking all elements of collections.

.circleci/config.yml, doc/build_docs.py, gpflow/experimental/check_shapes/argument_ref.py, gpflow/experimental/check_shapes/error_contexts.py, tests/integration/test_docs.py
Add a unit test that our documentation build doesn't produce any warnings.
(This doesn't build the notebooks, we have other tests for that.)
Basically this PR consists of:
1. Modify `doc/build_docs.py` with a flag that makes it fail if there are any warnings.
2. Modify `doc/build_docs.py` so that if `--max_notebooks` it generates an empty file, instead of no file, because the missing files would cause errors/warnings.
3. Add an integration test that runs `doc/build_docs.py` with `--max_notebooks=0` and `--fail_on_warning`.
4. Set up CircleCI to run the new test.
Currently this test fails, because our documentation is broken, but it should be fixed by #1856
I've set this up as a separate "fast" test on CircelCI - it seems like it takes about 3 minutes to run: 2 minutes to install GPflow …
=> Add test of documentation warnings.

gpflow/experimental/check_shapes/decorator.py, gpflow/experimental/check_shapes/exceptions.py, tests/gpflow/experimental/check_shapes/test_integration.py
Tensorflow has its own code for decorating functions and for code inspection, because of course they cannot do anything the easy way. This updates `check_shapes` to be compatible with that.
Fixes #1858
=> Make check_shapes play well with tf's custom code inspection.

doc/sphinx/conf.py, doc/update_versions.py
It had two problems:
1. (Embarrassingly) forgot to update `self._versions` in `_Versions.sort`.
2. New version of `pydata-sphinx-theme` has removed the `url_template`, and instead require each version to have an explicit `url` value.
=> Fix update_versions.py.

RELEASE.md, gpflow/base.py, gpflow/conditionals/util.py, gpflow/covariances/kufs.py, gpflow/experimental/check_shapes/checker.py, gpflow/likelihoods/base.py, gpflow/models/model.py, gpflow/utilities/multipledispatch.py, tests/gpflow/test_initial_value.py
Fixes #1881 
Apparently TensorFlow cannot compile code that has variables without a value. See #1881 .
This PR:
- Adds a unit test that all assignments have a value.
- Removes any cases of assignments without a value that we had.
- (And drive-by fixes a couple of unused imports...)
=> Stop using uninitialised variables.

RELEASE.md, doc/sphinx/notebooks/advanced/variational_fourier_features.pct.py, gpflow/covariances/kufs.py, gpflow/inducing_variables/inducing_variables.py, gpflow/inducing_variables/multioutput/inducing_variables.py, gpflow/posteriors.py, tests/gpflow/experimental/check_shapes/test_shapes.py, tests/gpflow/test_inducing_variables.py, tests/gpflow/utilities/test_multipledispatch.py
Add shape checking to the `inducing_variables` sub-package:
1. I don't know what's going on with that `kufs.py`. See: https://secondmind-ai.slack.com/archives/CUFMWJN4T/p1651748445091629
2. I use `get_shape.register` to define a shape of inducing variables.
3. This triggered some `mypy` warnings in `posteriors.py`, which I fix with a `cast`. `X_data` has type `Union[tf.Tensor, InducingVariables]`, though in practice they should never be `InducingVariables` at that point in the code.
4. Extended tests of `get_shapes`, as I though of some special cases I hadn't covered.
5. Extended tests of `InducingVariables`, particularly around shapes.
=> Add check_shapes to inducing_variables.

RELEASE.md, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/checker.py, gpflow/experimental/check_shapes/specs.py, gpflow/utilities/ops.py, tests/gpflow/experimental/check_shapes/test_checker.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/test_specs.py
Fixes: #1889
Support multiple variable-rank dimension specifications. For example:
```python
@check_shapes(
"a: [a_shape...]",
"b: [b_shape...]",
"return: [a_shape..., b_shape...]",  # <-- Previously not allowed.
)
def broadcasting_elementwise(
op: Callable[[tf.Tensor, tf.Tensor], tf.Tensor], a: tf.Tensor, b: tf.Tensor
) -> tf.Tensor:
""" Apply binary operation `op` to every pair in tensors `a` and `b`. """
```
This is more complexity than I'm really happy with, but GPflow uses that kind of shapes heavily, so we probably need to support it.
=> Support multiple variable-rank dimension specifications.

gpflow/conditionals/util.py, gpflow/experimental/check_shapes/checker.py, tests/conftest.py, tests/gpflow/test_monitor.py
Sometimes TensorFlow will (almost) silently not compile your code.
This PR adds a test that none of our other tests prints: "AutoGraph could not transform", and fixes the couple of cases there were discovered.
(Surprisingly TensorFlow *really* don't like type annotations...)
=> Make sure all code compiles correctly.

gpflow/experimental/check_shapes/error_contexts.py, tests/gpflow/experimental/check_shapes/test_bool_specs.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py
Make sure all `ErrorContext`s are hashable.
A couple of places we hash the error context, but actually they were not always hashable, leading to crashes. This PR ensure that all the `ErrorContext`s are hashable.
=> Make sure all ErrorContext-s are hashable.

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/bool_specs.py, gpflow/experimental/check_shapes/check_shapes.lark, gpflow/experimental/check_shapes/parser.py, tests/examples/test_check_shapes_examples.py, tests/gpflow/experimental/check_shapes/test_bool_specs.py, tests/gpflow/experimental/check_shapes/test_decorator.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/experimental/check_shapes/test_parser.py, tests/gpflow/experimental/check_shapes/utils.py
Add support for 'is None' and 'is not None' checks to check_shapes.
Again, not a feature I'm excited about supporting, but it's very much necessary to shape-check GPflow kernels.
=> Add support for 'is None' and 'is not None' checks to check_shapes.

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/parser.py, tests/gpflow/experimental/check_shapes/test_parser.py
Fixes: #1902
Make check_shapes add info-fields for arguments that don't have any.
=> Make check_shapes add info-fields for arguments that don't have any.

gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/checker.py, gpflow/experimental/check_shapes/config.py, gpflow/experimental/check_shapes/error_contexts.py, tests/examples/test_check_shapes_examples.py, tests/gpflow/experimental/check_shapes/conftest.py, tests/gpflow/experimental/check_shapes/test_config.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py
A couple of optimisations to `check_shapes` after looking at it through a profiler:
1. It turns out we were spending a lot of time computing hashes. Instead of having many dicts, each containing some information for each variable, we create a `_VariableState` structure, and have a single dict. This allows us to reduce many dict look-ups to a single call. (And is arguably more readable anyway...) In the process of this `_check_variable_use` got merged into `_parse_checks`.
2. Have a config option for whether to pre-compute file and line numbers for error-messages, defaulting to `False`, since this is particularly slow.
Together these seem to reduce the overhead of `check_shapes` by about 40%, which isn't as much as I'd like, but is better than nothing.
=> Micro optimisations of check_shapes.

.circleci/config.yml, tests/gpflow/experimental/check_shapes/test_integration.py
Start testing with the new TensorFlow 2.9.
Fixes: #1891
=> Support TensorFlow 2.9.

.pylintrc, RELEASE.md, gpflow/experimental/check_shapes/__init__.py, gpflow/experimental/check_shapes/shapes.py, gpflow/inducing_variables/inducing_variables.py, tests/examples/test_check_shapes_examples.py, tests/gpflow/experimental/check_shapes/test_error_contexts.py, tests/gpflow/experimental/check_shapes/test_integration.py, tests/gpflow/experimental/check_shapes/utils.py
Basically the interaction of TensorFlow and `@singledispatch` is super flaky, so I'm removing `@singledispatch` from `check_shapes`.
=> Stop using singledispatch because TensorFlow cannot compile it.

gpflow/models/cglb.py, gpflow/models/gplvm.py, gpflow/models/gpmc.py, gpflow/models/gpr.py, gpflow/models/model.py, gpflow/models/sgpr.py, gpflow/models/vgp.py, gpflow/posteriors.py, gpflow/utilities/__init__.py, gpflow/utilities/model_utils.py, tests/gpflow/models/test_gpr_posterior.py, tests/gpflow/models/test_sgpr_posterior.py, tests/gpflow/models/test_vgp_posterior.py, tests/gpflow/utilities/test_model_utils.py
We have some methods that do not support `full_cov=True` and many that do not support `full_output_cov=True`. Right now some of those methods raise various error messages, but many also silently ignore the invalid argument.
With this PR we systematically raise the same error message in these cases.
=> Consistently raise errors where full_output_cov isn't supported.

CONTRIBUTORS.md, RELEASE.md, gpflow/utilities/traversal.py, setup.py, tests/gpflow/utilities/test_traversal.py
**Related issue(s)/PRs:**  Contributes to #1850
This PR introduces basic support for Apple Silicon MacOS. This is achieved by pulling `tensorflow-macos` dependency instead of regular `tensorflow` at setup time.
This has been tested on an Macbook Pro 2021 M1 Pro, `python3.8`. 
* Update `setup.py` to dynamically decide on the `tensorflow` source depending on the platform
* Changes in `gpflow/utilities/traversal.py` and `test_traversal.py` come from the common type of errors that `0.999999 != 1.0` and representation of floating point numbers.
No alternatives have been considered. Please let me know if there are any.
```console
python3.8 -m venv gpflow-py38
source gpflow-py38/bin/activate
python -m pip …
```
=> Experimental Apple Silicon (M1) support

RELEASE.md, doc/sphinx/notebooks/advanced/varying_noise.pct.py, gpflow/likelihoods/base.py, gpflow/likelihoods/multiclass.py, gpflow/likelihoods/multilatent.py, gpflow/likelihoods/scalar_continuous.py, gpflow/likelihoods/scalar_discrete.py, gpflow/models/cglb.py, gpflow/models/gpmc.py, gpflow/models/model.py, gpflow/models/sgpmc.py, gpflow/models/svgp.py, gpflow/models/vgp.py, gpflow/quadrature/deprecated.py, tests/gpflow/likelihoods/test_heteroskedastic.py, tests/gpflow/likelihoods/test_heteroskedastic_constant_variance.py, tests/gpflow/likelihoods/test_likelihoods.py, tests/gpflow/likelihoods/test_multiclass.py, tests/gpflow/likelihoods/test_switched_likelihood.py
Add an `X` parameter to the `Likelihood` class methods.
This will make it easy/possibly to write heteroskedastic likelihoods.
I plan to do more with heteroskedastic likelihoods in downstream PRs, but I want to get the "controversial" part of it out of the way first.
Basically this is the controversial part, because this is a breaking change.
To guesstimate the scale of the breakage, consider our notebooks. We have 35 notebooks doing all kinds of advanced stuff. A single one of those breaks.
=> Add an X parameter to the Likelihood.

RELEASE.md, gpflow/experimental/check_shapes/decorator.py, tests/gpflow/experimental/check_shapes/test_integration.py
Fixes: #1864
Fixes: #1936
Related to: #1858
Make `tf_decorator.make_decorator` configurable.
It was initially added to play better with Keras. However, it seems to also cause problems. So, I suggest hiding it behind a function parameter.
=> Make `tf_decorator.make_decorator` configurable.

RELEASE.md, gpflow/posteriors.py, tests/gpflow/posteriors/test_posteriors.py
Fixes: #1959
Our previous `GPRPosterior` and `SGPRPosterior` objects computes matrix inverses by solving against an identity matrix. This is not numerically stable.
In this PR I rewrite those posterior objects. My strategy has simply been to take the old (proven) `predict_f` method, and copy everything that does not depend on `Xnew` to `_precompute` and the rest to `_conditional_with_precompute`. `_conditional_fused` then just becomes a composition of `_precompute` and `_conditional_with_precompute`, which is exactly the same code as the old `predict_f`.
I've benchmarked the new code using our new benchmarking framework:
- The timings are generally on the same order of magnitude.
- Often the old code is a bit faster.
- Except sometimes the new code is massively faster for GPR on a GPU.
=> Rewrite (S)GPRPosterior for numerical stability.

gpflow/functions.py
TensorFlow complains that it cannot compile our `Polynomial` function, because it doesn't like generators, so update the relevant code to create a list instead.
Also fix a couple of documentation formatting issues.
=> Remove generator from Polynomial function.

.circleci/config.yml, RELEASE.md, tests/gpflow/experimental/check_shapes/test_integration.py
Start testing GPflow for TensorFlow 2.10.
Also slight update to format of `pip install`.
=> Upgrade for TensorFlow 2.10.

.circleci/config.yml
Use CircleCI workspaces to cache the GPflow installation (per pipeline run), to reduce pipeline run-time slightly.
=> Install GPflow fewer times during CI.

.circleci/config.yml, tests_requirements.txt
Fixes: #1989
1. Most importantly: Disallow `sphinx_autodoc_typehints` 1.19.3 - it has a crashing bug that is blocking our CI pipeline.
2. Disallow `pydata-sphinx-theme` 0.10 as it mis-formats tables in our documentation.
3. Un-fix the Python 3.10 version - as there's a new, fixed, `mypy`.
4. Re-organising of requirements - and removed repeated `jupytext` dependency.
=> Various build cleanups.

RELEASE.md, gpflow/experimental/check_shapes/shapes.py, gpflow/inducing_variables/multioutput/inducing_variables.py, gpflow/quadrature/base.py, tests/gpflow/experimental/check_shapes/test_shapes.py, tests/gpflow/test_inducing_variables.py
Various smaller stuff to better support GPflux:
1. Extract shapes of `tfp.python.layers.internal.distribution_tensor_coercible._TensorCoercible`.
2. Allow `FallbackSeparateIndependentInducingVariables` to have children with different shapes.
3. Allow input and output batches on `GaussianQuadrature` to be different.
=> Various fixes for compatibility for GPflux.

tests/conftest.py
Seems there's been some kind of updated library that's now causing a `mypy` error. Maybe it's a new `pytest`?
=> Fix mypy error.

benchmark/benchmark_api.py, tests/gpflow/models/test_model_predict.py, tests/integration/test_notebooks.py, tests_requirements.txt
**Related issue(s)/PRs:** Attempt at solving #2015 
Update the `#type: ignore` to specifically ignore the new `type-abstract` error added to mypy this morning.  This is required because mypy is incorrectly identifying SGPR as abstract.
There's also an error relating to implicit exports which doesn't appear to have been there before which I've fixed, plus addition of scikit-learn as the sklearn package wasn't correctly pulling in the necessary dependencies (and is probably unrelated but was required to make a PR that would pass CI).
See #2015 for details of the error.  This PR will trigger the CI tests that will demonstrate whether this fix works.
=> Updated to compensate for new mypy version

CONTRIBUTORS.md, RELEASE.md, benchmark/benchmark_api.py, gpflow/utilities/misc.py, tests/conftest.py, tests/gpflow/models/test_model_predict.py, tests/gpflow/utilities/test_misc.py, tests/integration/test_notebooks.py, tests_requirements.txt
**PR type:** bugfix 
It seems that `to_default_float` can result in a loss of precision when the input value is a python float. This was previously not the case because `to_default_float` used to use gpflow's `cast` function internally, which used `tf.convert_to_tensor(..., dtype=tf.float64)` in the case that the input is a python float. 
However, this function was declared obsolete in gpflow 2.6.1, and was replaced by Tensorflow's `tf.cast` instead. The implementation of `tf.cast` is such that it converts the python float to a tf.float32 tensor (thereby losing precision), which it then casts to tf.float64.
You can see the essence of the problem as follows (note that 0.99999999 and 1.0 are distinct at 64 bit precision, so the fact that the lhs is rounded to 1.0 demonstrates a loss of …
=> Avoid loss of precision in to_default_float when input is a python float

benchmark/grouping.py
[**Related issue(s)/PRs**](https://github.com/python/cpython/issues/91267)
The bug in cpython3.8 linked above is causing our benchmarking to fail.  This isn't really fixable by us, so I've added a warning comment to prevent people banging their heads against this issue.
=> Noted cpython 3.8 bug

.circleci/config.yml
Use PyPi [token](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#id71) for uploading the GPflow's python package via CircleCI instead of the password.
=> Use PyPi token for package uploading

gpflow/optimizers/scipy.py
We have observed some instability during model training, where occasionally the SGPR model loss is unexpectadly very poor. We have tracked the problem down to how the _gpflow_ wrapper calls the _scipy_ optimiser (using BFGS in our case).
The wrapper uses `tf.Variable`s for the model hyperparameters and these are updated on every evaluation of the training loss. On those occasions where the BFGS line-search fails for an iteration, the _scipy_ optimiser returns the previous good point that it found and sets appropriate flags in the `OptimizeResult` class. However, the model hyperparameters will have the value of the last evaluation of the failed line-search, which can be quite poor. One solution is for the caller to look at the returned result, realise that there was a …
=> Always copy the final point found by scipy

RELEASE.md, doc/generate_module_rst.py
**Related issue(s)/PRs:** resolves #2056 
* Fix issues with API doc generation for `SquaredExponential` and `Constant` kernels.
* Due to use of aliases, previously the doc generation for these two kernels was missing. Only the minimal docs for `RBF` and `Bias` aliases (respectively) were present.
Doc example with missing classes: https://gpflow.github.io/GPflow/2.7.1/api/gpflow/kernels/index.html#gpflow-kernels-rbf
Generated fixed documentation locally and checked the classes are present.
=> Fix api doc generation for aliases

.circleci/config.yml, .pylintrc, RELEASE.md, gpflow/config/__config__.py, gpflow/kernels/categorical.py, tests/gpflow/expectations/test_expectations.py, tests/gpflow/models/test_methods.py, tests/gpflow/models/test_sgpr.py, tests/gpflow/models/test_svgp.py, tests/integration/test_linear_noise.py
Fixes: #2007 
Fixes: #2078 
Test GPflow with Python 3.11.
I had to remove some `@dataclass` from some tests, because a dataclass cannot have default values that are numpy arrays in Python 3.11 (because it has more stricts tests that the default values must be immutable). Actually the values were only used statically anyways, so `@dataclass` was not needed.
Also removed some unused imports.
=> Test GPflow with Python 3.11.

benchmark/plotters.py, gpflow/base.py, gpflow/monitor/tensorboard.py, gpflow/optimizers/natgrad.py, tests/gpflow/test_monitor.py
Fix mypy issues exposed by recent third party package updates.
=> Fix newly exposed mypy issues

RELEASE.md, gpflow/utilities/traversal.py, tests/gpflow/utilities/test_traversal.py
PR #1924 resulted in values in print summary being truncated to 5 decimal places, which is a problem for eg small variances. This PR prevents rounding for values less than 1.
Arguably any rounding is unnecessary. However, the print summary tests currently have hardcoded expecations and fail when run on MacOS if the values aren't rounded. Since the values are meant to be human readable there is no harm in rounding large values.
=> Don't round small values in print summary

gpflow/optimizers/scipy.py, tests/gpflow/optimizers/test_scipy.py
The recently introduced compile cache prevents scipy optimizers from being deepcopied. This can be worked around by simply not pickling them.
See tests
Bugfix: allow Scipy optimizer to be deepcopied when using compile cache.
=> Don't try to save the compile cache when pickling Scipy optimizer

.circleci/config.yml, RELEASE.md, doc/sphinx/notebooks/advanced/gps_for_big_data.pct.py, doc/sphinx/notebooks/advanced/heteroskedastic.pct.py, doc/sphinx/notebooks/advanced/natural_gradients.pct.py, doc/sphinx/notebooks/getting_started/monitoring.pct.py, doc/sphinx/notebooks/getting_started/parameters_and_their_optimisation.pct.py, doc/sphinx/notebooks/tailor/external-mean-function.pct.py, doc/sphinx/notebooks/tailor/gp_nn.pct.py, doc/sphinx/notebooks/tailor/mixture_density_network.pct.py, gpflow/__init__.py, gpflow/keras.py, gpflow/models/training_mixins.py, gpflow/optimizers/natgrad.py, gpflow/utilities/misc.py, setup.py, tests/gpflow/conditionals/test_uncertain_conditional.py, tests/gpflow/models/test_svgp.py, tests/gpflow/test_all.py, tests/gpflow/test_inducing_variables.py, tests/gpflow/test_monitor.py, tests/gpflow/utilities/test_training_loop.py, tests/gpflow/utilities/test_traversal.py
**Related issue(s)/PRs:** #2106 
Add support for Tensorflow 2.16.1. Since this uses Keras 3 as the default keras, I've had to:
- explicitly depend on `tf_keras` (Keras 2) which is no longer installed by default; fortunately this can done by specifying the `[tf]` extra with `tensorflow-probability` (as TFP also requires Keras 2)
- switch all uses of `tf.keras` to use `tf_keras` instead if it's available
A simpler approach would be to make `tf.keras` automatically use Keras 2 by setting the `TF_USE_LEGACY_KERAS` environment variable in `__init__.py`. However, this would prevent gpflow from being used alongside packages that use Keras 3.
=> Bump max_tf_ver to 2.16.1

.circleci/config.yml, benchmark/plotters.py
=> Update prod tf version to 2.11
